<?php
/**
 * Backend header view script
 */
?>

<div id="header">
<?php 
// Navigation HTML
$options = array(
	'width'=>' span6',
	'user'=>$this->user,
);

$this->navigation()->menu( $this->mainmenu )
	->setPartial( array('partials/admin/nav.phtml', 'admin'));
echo $this->navigation()
	->setInjectTranslator(false)
	->setMaxDepth(2)
	->menu();

// Logout form
$form = new Xmltv_Form_Logout(array(
	'action'=>$this->baseUrl('admin/auth/logout'),
	'submit_text'=>'Выход',
));
echo $form;
?>
</div>



