<?php
/**
 * @uses Zend_Navigation_Page_Mvc
 */
//var_dump($this->container);
//die(__FILE__.': '.__LINE__);
?>
<ul class="nav nav-pills">
<?
foreach ($this->container as $page) {
    
	if (count($page->getPages())) {
	    foreach ($page->getPages() as $subPage) {
			if ($this->isAllowed( $subPage->getResource() )){
				?>
				<li class="<?php echo ($subPage->isActive(true) ? 'active' : '') ?>">
					<a href="<?php echo $this->baseUrl( $subPage->getHref() ) ?>"><?php echo $subPage->getLabel() ?></a>
				</li>
				<?php 
			}
		}
	} else {
		if ($this->isAllowed( $page->getResource() )){
			$linkAttrHref = $this->baseUrl( $page->get('module').'/'.$page->get('controller').'/'.$page->get('action'));
		?>
	    <li class="<?php echo ($page->isActive(true) ? 'active' : '') ?>">
	    	<a href="<?php echo $linkAttrHref; ?>"><?php echo $page->getLabel() ?></a>
	    </li>
		<?php 
		}
	}
}
?>
</ul>