
<h1>Администрирование</h1>

<div id="cpanel">
	<ul class="nav nav-pills">
		<li><a href="/admin/programs">Программы</a></li>
		<li class="dropdown">
			<a class="dropdown-toggle" href="#" data-toggle="dropdown">Фильмы<b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li><a href="/admin/movies">Список</a></li>
				<li><a href="/admin/movies/grab">Скачать описания</a></li>
			</ul>
		</li>
		<li class="dropdown">
			<a class="dropdown-toggle" href="#" data-toggle="dropdown">Сериалы<b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li><a href="/admin/series">Список</a></li>
				<li><a href="/admin/series/grab">Скачать описания</a></li>
			</ul>
		</li>
		<li class="dropdown">
			<a class="dropdown-toggle" href="#" data-toggle="dropdown">Актеры<b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li><a href="/admin/actors">Список</a></li>
				<li><a href="/admin/actors/duplicates">Дубликаты</a></li>
			</ul>
		</li>
		<li class="dropdown">
			<a class="dropdown-toggle" href="#" data-toggle="dropdown">Режиссеры<b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li><a href="/admin/directors">Список</a></li>
				<li><a href="/admin/directors/duplicates">Дубликаты</a></li>
			</ul>
		</li>
		<li><a href="/admin/channels">Каналы</a></li>
		<li><a href="/admin/comments">Комменты</a></li>
		<li><a href="/admin/import">Импорт XML</a></li>
	</ul>
</div>

<?php

?>