<table>
	<caption>Действия</caption>
	<tbody>
		<tr>
			<td class="task" style="font-weight:bold;">Скачать описания сериалов</td>
			<td class="link"><a href="/admin/grab/movies">/admin/grab/movies</a></td>
		</tr>
		<tr>
			<td class="task" style="font-weight:bold;">Скачать описания фильмов</td>
			<td class="link"><a href="/admin/grab/series">/admin/grab/series</a></td>
		</tr>
		<tr>
			<td class="task" style="font-weight:bold;">Импорт XML из файла</td>
			<td class="link"><a href="/admin/import">/admin/import</a></td>
		</tr>
		<tr>
			<td class="task" style="font-weight:bold;">Работа с дубликатами</td>
			<td class="link"><a href="/admin/duplicates">/admin/duplicates</a></td>
		</tr>
	</tbody>
</table>

<?php

?>