<?php
/**
 * Frontpage view script
 * 
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: frontpage.phtml,v 1.7 2013-02-15 00:44:03 developer Exp $
 *
 */
/*
var_dump($this->is_frontpage);
die(__FILE__.': '.__LINE__);

$this->headTitle( 'Программа всех каналов телевидения на сегодня и текущую неделю.' );
$this->headMeta()
	->setName( 'keywords', Zend_Registry::get('site_config')->site->get('keywords', 'телепрограмма,каналы,программа тв,каналы,телеканалы,каналы тв') )
	->appendName( 'description', Zend_Registry::get('site_config')->site->get('description', 'Программа всех каналов телевидения на сегодня и текущую неделю.') );
$this->inlineScript()
	->appendFile("http://www.directadvert.ru/show.cgi?adp=85452&div=DIV_DA_85452"); //directadvert frontpage
?>

<div class="brand span12">
	<?php $tag = 'p'; if ($this->pageclass=='allchannels') $tag='h1'; ?>
	<<?php echo $tag ?>>Rutvgid.ru :: <a href="<?php echo $this->url(array(), 'default_frontpage_index'); ?>" title="Телепрограмма на все телеканалы">Программа передач телеканалов России, Украины и СНГ.</a><br />
	Онлайн-видео на любой вкус</<?php echo $tag ?>>
</div>

<div>
	<gcse:searchbox></gcse:searchbox>
</div>
*/ ?>