<?php
/**
 * View script for paginated articles list
 */
?>
<h2 class="page_heading">Статьи</h2>

<form id="tableForm" action="<?php echo $this->baseUrl('admin/content/edit') ?>" method="post">
	
	<div class="table-menu">
		<?php 
		$this->navigation()->menu( $this->actions_menu )
			->setPartial( array('partials/actions-menu.phtml', 'admin'));
		echo $this->navigation()
			->setMaxDepth(2)
			->setInjectTranslator(false)
			->menu();
		?>
	</div>

<?php 
if (count($this->list)){
	?>
	<div class="items-table">
		<table class="table table-striped table-bordered table-hover table-condensed span12"  style="font-size:x-small;">
			<thead>
				<tr>
					<th width="2%"><input type="checkbox" name="toggle" /></th>
					<th width="2%">#</th>
					<th style="text-align:center;" width="40%">Заголовок</th>
					<th style="text-align:center;" colspan="4">Статистика по символам</th>
					<th style="text-align:center;" colspan="3" >Категории статьи</th>
					<th style="text-align:center;">Теги</th>
					<th style="text-align:center;">MD</th>
					<th style="text-align:center;">Вкл</th>
					<th>ID</th>
				</tr>
				<tr>
					<th colspan="3"></th>
					<th style="text-align:center;">Загл</th>
					<th style="text-align:center;">Лид</th>
					<th style="text-align:center;">Текст</th>
					<th style="text-align:center;">Всего</th>
					<th style="text-align:center;">Контент</th>
					<th style="text-align:center;">Каналы</th>
					<th style="text-align:center;">Программы</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
					<th>&nbsp;</th>
				</tr>
			</thead>
			<tbody>
			<?php 
			$c=0;
			foreach ($this->list as $item){
				$sq = $this->escape('■');
				?>
				<tr>
					<td><input type="checkbox" id="<?php printf('cb%s', $c); ?>" name="idx[]" value="<?php echo (int)$item['id']; ?>" /></td>
					<td><?php echo ($c+1); ?></td>
					<td><a href="<?php echo $this->baseUrl( 'admin/content/edit?do=edit&idx[]='.$item['id'] ); ?>">
						<?php echo html_entity_decode( $this->escape( $item['title'] ) ); ?></a></td>
					<td style="text-align:right;"><?php echo Xmltv_String::strlen( $item['title'] ); ?></td>
					<td style="text-align:right;">
						<?php $introLen = (int)Xmltv_String::strlen( preg_replace('/[\p{Common}\s]+/u', '', $item['intro'] ) );
						echo $introLen; ?>
					</td>
					<td style="text-align:right;">
						<?php $bodyLen = (int)Xmltv_String::strlen( preg_replace('/[\p{Common}\s]+/u', '', $item['body'] ));
						echo $bodyLen; ?>
					</td>
					<td style="text-align:right;"><b><?php echo $introLen+$bodyLen; ?></b></td>
					<td><?php echo $item['content_cat_title'] ?></td>
					<td><?php echo $item['channel_cat_title'] ?></td>
					<td><?php echo $item['program_cat_title'] ?></td>
					<td style="text-align:center;"><?php echo ((bool)$item['tags']!==false) ? '<span style="color:green">'.$sq.'</span>' : '<span style="color:red">'.$sq.'</span>' ;  ?></td>
					<td style="text-align:center;">
						<?php echo (empty($item['metadesc'])) ? '<span style="color:red">'.$sq.'</span>' : '<span style="color:green">'.$sq.'</span>' ;  ?>
					</td>
					<td style="text-align:center;"><?php echo (false === (bool)$item['published']) ? '<span style="color:red; font-weight: bold;">'.$this->escape('○').'</span>' : '<span style="color:green; font-weight: bold;">'.$this->escape('●').'</span>' ; ?></td>
					<td><?php echo (int)$item['id']; ?></td>
				</tr>
				<?php 
				$c++;
			} ?>
			</tbody>
			<tfoot>
				<tr>
					<td colspan="14" style="text-align:center;">
						<?php echo $this->paginationControl( $this->pagenav, 'Sliding', 'partials/pagination.phtml', array() ); ?>
					</td>
				</tr>
			</tfoot>
		</table>
	</div>
	<?php 
}
?>
	<input type="hidden" name="do" value="" />
	
</form>