<?php
/**
 * 
 * Featured channels block partial script
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: featured-channels.phtml,v 1.3 2013-01-19 10:11:13 developer Exp $
 */

$conf  = Zend_Registry::get('site_config');
$order = $conf->featured->channels->get('order', 'ch_id')=='ch_id' ? 'ch_id' : 'title' ;
$cols  = (int)$conf->featured->channels->get('cols', 4);
$total = (int)$conf->featured->channels->get('amount', 20);
$colW  = floor((100-$cols)/$cols);

$table = new Xmltv_Model_DbTable_Channels();
/**
 * 
 * @var Zend_Cache_Core
 */
$cache = new Xmltv_Cache();
if ((bool)Zend_Registry::get('site_config')->cache->system->get('enabled')===true){
    $hash = Xmltv_Cache::getHash('featuredchannels');
    $f = '/Channels';
    if (($list = $cache->load($hash, 'Core', $f))===false) {
        $list = $table->getFeatured($order, $total);
        $cache->save($list, $hash, 'Core', $f);
    }
} else {
    $list   = $table->getFeatured($order, $total);
}

$css = "ul#featured_channels { }
ul#featured_channels li { list-style:none; display: block; float: left; width: ".$colW."%; }";

?>
<style>
<?php echo $css; ?>
</style>

<ul id="featured_channels">
	<?php  
	for ( $i=0; $i<count($list); $i++ ) {
		$linkText = $this->truncateString( $list[$i]->title, 25 ).' сегодня';
		$url = $this->url(array('channel'=>Xmltv_String::strtolower($list[$i]->alias)), 'default_listings_day-listing');
		if (($i%$cols==$cols-1) || $i==(count($list)-1)) {
			echo '<li class="lastcol"><a href="'.$url.'">'.$linkText.'</a></li>';
		} else {
			echo '<li><a href="'.$url.'">'.$linkText.'</a></li>';
		}
	}
	?>
</ul>