<?php
/**
 * 
 * Featured channels block partial script
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: featured-channels.phtml,v 1.2 2012-12-27 17:04:37 developer Exp $
 */
$config = new Zend_Config_Ini(APPLICATION_PATH . '/configs/site.ini', APPLICATION_ENV);
$config = $config->featured->channels;
$order  = $config->get('order', 'ch_id')=='ch_id' ? 'ch_id' : 'title' ;
$cols   = (int)$config->get('cols', 4);
$total  = (int)$config->get('amount', 20);
$colW   = floor((100-$cols)/$cols);
$table  = new Xmltv_Model_DbTable_Channels();
$list   = $table->getFeatured($order, $total);
$css = "ul#featured_channels { }
ul#featured_channels li { list-style:none; display: block; float: left; width: ".$colW."%; }";

?>
<style>
<?php echo $css; ?>
</style>

<ul id="featured_channels">
	<?php  
	for ( $i=0; $i<count($list); $i++ ) {
		$linkText = $this->truncateString( $list[$i]->title, 25 ).' сегодня';
		$url = $this->url(array('channel'=>Xmltv_String::strtolower($list[$i]->alias)), 'default_listings_day-listing');
		if (($i%$cols==$cols-1) || $i==(count($list)-1)) {
			echo '<li class="lastcol"><a href="'.$url.'">'.$linkText.'</a></li>';
		} else {
			echo '<li><a href="'.$url.'">'.$linkText.'</a></li>';
		}
	}
	?>
</ul>