<?php
/**
 * 
 * Featured channels block partial script
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: featured-channels.phtml,v 1.4 2013-02-15 00:44:02 developer Exp $
 */

$conf  = Zend_Registry::get('site_config');
$order = $conf->featured->channels->get('order', 'ch_id')=='ch_id' ? 'ch_id' : 'title' ;
$cols  = (int)$conf->featured->channels->get('cols', 4);
$total = (int)$conf->featured->channels->get('amount', 20);
$colW  = floor((100-$cols)/$cols);
$css = "ul#featured_channels { }
ul#featured_channels li { list-style:none; display: block; float: left; width: ".$colW."%; }";

?>
<style>
<?php echo $css; ?>
</style>

<ul id="featured_channels">
	<?php  
	for ( $i=0; $i<count($this->list); $i++ ) {
		$linkText = $this->truncateString( $this->list[$i]['title'], 25 ).' сегодня';
		$url = $this->url( array('channel'=>Xmltv_String::strtolower( $this->list[$i]['alias'])), 'default_listings_day-listing');
		if (($i%$cols==$cols-1) || $i==(count($this->list)-1)) {
			echo '<li class="lastcol"><a href="'.$url.'">'.$linkText.'</a></li>';
		} else {
			echo '<li><a href="'.$url.'">'.$linkText.'</a></li>';
		}
	}
	?>
</ul>