<?php

?>


<div class="row-fluid">
	<div>
		<div class="brand span10">
			<?php $tag = 'p'; if ($this->pageclass=='allchannels') $tag='h1'; ?>
			<<?php echo $tag ?>>Rutvgid.ru :: <a href="<?php echo $this->url(array(), 'default_frontpage_index'); ?>" title="Телепрограмма на все телеканалы">Программа передач телеканалов России, Украины и СНГ.</a>
		</div>
	</div>
	<div class="span2 pull-right">
		<div id="vk_like"></div>
	</div>
</div>

<ul id="fpnav" class="row-fluid">
	<li class="span3">
		<a href="<?php echo $this->url(array(), 'default_channels_list')  ?>" title="Телепрограмма всех каналов на сегодня">
			<strong>Все каналы</strong>
		</a>
	</li>
	<li class="span3">
		<a href="<?php echo $this->url(array(), 'default_movies_week') ?>" title="Новые фильмы недели">
			<strong>Фильмы на этой неделе</strong>
		</a>
	</li>
	<li class="span3">
		<a href="<?php echo $this->url(array(), 'default_series_week') ?>">
			<strong>Сериалы на этой неделе</strong>
		</a>
	</li>
	<li class="span3 lastcol">
		<a href="<?php echo $this->url(array(), 'default_programs_premieres-week') ?>">
			<strong>Премьеры недели</strong>
		</a>
	</li>
	<?php /*
	<li class="span4">
		<a href="<?php echo $this->url(array(), 'default_persons_actors') ?>">
			<span>Актеры</span>
		</a>
	</li>
	<li class="span4 lastcol">
		<a href="<?php echo $this->url(array(), 'default_persons_directors') ?>">
			<span>Режиссеры</span>
		</a>
	</li>
	*/ ?>
	
</ul>