<?php

?>
<ul id="fpnav" class="span12">
	<li class="span4">
		<a href="<?php echo $this->url(array(), 'default_channels_list')  ?>" title="Телепрограмма всех каналов на сегодня">
			<span>Каналы</span>
		</a>
	</li>
	<li class="span4">
		<a href="<?php echo $this->url(array(), 'default_movies_movies-week') ?>" title="Новые фильмы недели">
			<span>Фильмы на этой неделе</span>
		</a>
	</li>
	<li class="span4 lastcol">
		<a href="<?php echo $this->url(array(), 'default_series_series-week') ?>">
			<span>Сериалы на этой неделе</span>
		</a>
	</li>
	<li class="span4">
		<a href="<?php echo $this->url(array(), 'default_programs_premieres-week') ?>">
			<span>Премьеры недели</span>
		</a>
	</li>
	<li class="span4">
		<a href="<?php echo $this->url(array(), 'default_persons_actors') ?>">
			<span>Актеры</span>
		</a>
	</li>
	<li class="span4 lastcol">
		<a href="<?php echo $this->url(array(), 'default_persons_directors') ?>">
			<span>Режиссеры</span>
		</a>
	</li>
</ul>

<div id="DIV_DA_85452" class="span12"></div>