<?php
/**
 * @author  Antony Repin
 */
?>

<div class="row-fluid" id="header">
	<div class="navbar span12">
		<div class="navbar-inner">
            <ul class="nav nav-pills">
                <li><a href="<?= $this->baseUrl('/телепрограмма') ?>">Все каналы</a></li>
                <?php 
                $i=0;
                foreach ($this->navData as $cat){
                    ?>
                <li class="dropdown">

                    <a class="dropdown-toggle"
                       data-toggle="dropdown" 
                       href="каналы/<?= $this->escape( $cat['alias'] ) ?>"><?= $this->escape( $cat['title'] ) ?>
                       <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <?php 
                        foreach ($cat['channels'] as $c){
                            ?>
                        <li>
                            <a href="/телепрограмма/<?= $this->escape($c['alias']) ?>"
                               class="pull-left" 
                               style="vertical-align: middle;">
                                <?= $this->escape($c['title']) ?>
                                <?php if ((int)$c['stream']>0){ ?>
                                    <span class="btn btn-mini">онлайн</span>
                                <?php } ?>
                            </a>
                        </li>
                            <?php
                        }
                        ?>
                    </ul>
                </li>
                    <?php
                    $i++;
                }
                ?>
                <li><a href="<?= $this->baseUrl('/') ?>">Rutvgid.ru</a></li>
            </ul>
		</div>
	</div>
</div>

<div class="row-fluid">
    <div class="yashare-auto-init pull-left" data-yashareL10n="ru" data-yashareType="button" data-yashareQuickServices="vkontakte,facebook,twitter,odnoklassniki,moimir,moikrug,gplus,surfingbird"></div>
    <div class="pull-right">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- 728x90 -->
        <ins class="adsbygoogle"
             style="display:inline-block;width:728px;height:90px"
             data-ad-client="ca-pub-1744616629400880"
             data-ad-slot="5607721396"></ins>
        <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    </div>
</div>
