<?php
/**
 * Чердак страницы
 *
 * @author  Antony Repin
 * @version $Id: header.phtml,v 1.11 2013-04-03 04:08:16 developer Exp $
 *
 */
?>

<div class="row" id="header">

	<div class="navbar span12">
		<div class="navbar-inner">
            <ul class="nav nav-pills">
                <?php 
                $i=0;
                foreach ($this->nav_data as $cat){
                    ?>
                <li class="dropdown">
                    <a href="<?= $this->baseUrl('/каналы/'.$cat['alias']) ?>"><?= $cat['title'] ?></a>
                </li>
                    <?php
                }
                ?>
                <li><a href="<?= $this->baseUrl('/телепрограмма') ?>">Все каналы</a></li>
            </ul>
		</div>
	</div>
	
	<?php 
	// Login form
	if (isset($this->user) && $this->isAllowed('default:auth')){
	    $wrapClass = 'span3';
		if ($this->user->role == 'guest') {
		    $form = new Xmltv_Form_Login( array(
				'action'=>$this->url( array(), 'default_user_login'),
				'wrap_class'=>$wrapClass,
			));
		} else {
			$form = new Xmltv_Form_Logout(array(
				'action'=>$this->url( array(), 'default_user_logout'),
				'wrap_class'=>$wrapClass,
			));
		}
		echo $form;
	}
	?>
    
</div>

<div class="row">
    <div class="yashare-auto-init span12" data-yashareL10n="ru" data-yashareType="button" data-yashareQuickServices="vkontakte,facebook,twitter,odnoklassniki,moimir,moikrug,gplus,surfingbird"></div>
</div>

