<?php
/**
 * Чердак страницы
 *
 * @author  Antony Repin
 * @version $Id: header.phtml,v 1.11 2013-04-03 04:08:16 developer Exp $
 *
 */
?>

<div class="row-fluid" id="header">

	<div class="navbar span12">
		<div class="navbar-inner">
            <ul class="nav nav-pills">
                <?php 
                $i=0;
                foreach ($this->nav_data as $cat){
                    ?>
                <li class="dropdown">
                    <a class="dropdown-toggle"
                       data-toggle="dropdown" 
                       href="каналы/<?= $this->escape( $cat['alias'] ) ?>"><?= $this->escape( $cat['title'] ) ?>
                       <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <?php 
                        foreach ($cat['channels'] as $c){
                            ?>
                        <li>
                            <a href="телепрограмма/<?= $this->escape($c['alias']) ?>"
                               class="pull-left" 
                               style="vertical-align: middle;">
                                <?= $this->escape($c['title']) ?>
                                <?php if ((int)$c['stream']>0){ ?>
                                    <span class="btn btn-mini">онлайн</span>
                                <?php } ?>
                            </a>
                        </li>
                            <?php
                        }
                        ?>
                    </ul>
                </li>
                    <?php
                }
                ?>
                <li><a href="<?= $this->baseUrl('/телепрограмма') ?>">Все каналы</a></li>
            </ul>
		</div>
	</div>
	
    <div class="yashare-auto-init span12" data-yashareL10n="ru" data-yashareType="button" data-yashareQuickServices="vkontakte,facebook,twitter,odnoklassniki,moimir,moikrug,gplus,surfingbird"></div>
    
</div>
