<?php
/**
 * Left sidebar view script
 * 
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: sidebar-left.phtml,v 1.14 2013-04-06 22:35:03 developer Exp $
 *
 */
?>
<div class="span<?= $this->spans ?>" id="col_l">
    
    <?php 
    //Top broadcasts block
    if (isset($this->bcTop) && !empty($this->bcTop)) {
        ?>
    <div id="topBroadcasts" class="module hidden-phone">
        <h4>Топ 20 недели</h4>
        <ul>
            <?php 
            foreach ($this->bcTop as $bc){
                try {
                    $hrefUrl = $this->url( array('channel'=>$this->escape($bc['channel_alias']), 'alias'=>$this->escape($bc['alias'])), 'default_listings_broadcast-week');
                } catch (Exception $e) {
                    throw new Zend_Exception("Cannot assemble URL", 500, $e);
                }
                    ?>
            <li>
                <img src="<?= $this->baseUrl( 'images/channel_logo/'.$this->escape($bc['channel_icon']) ) ?>" />
                <a href="<?= $hrefUrl ?>"
                    title="<?= $this->escape( sprintf("«%s» на канале «%s» на этой неделе", $bc['title'], $bc['channel_title'])) ?>">
                        <?= $this->escape($bc['title']) ?>
                </a>
            </li>
            <?php 	
            }
            ?>
        </ul>
    </div>	
        <?php 
    }
    ?>
    
    <?php
    if (isset($this->channelNews) && (bool)$this->channelNews!==false){ 
        ?>
    <div class="module channelNews">
            <h4>Новости канала</h4>
        <?php
        $i=0;
        foreach ($this->channelNews as $n){
            $vid = $this->videos[$i];
            $thumb = $vid['thumbs'][rand( 0, count( $vid['thumbs'])-1)];
            $href1 = $this->url(array('alias'=>$vid['alias'], 'id'=>$vid['rtvg_id']), 'default_videos_show-video');
            $href2 = $this->escape($n['link']);
            ?>
        <div class="message">
            
            <?php if (is_a($n['pubDate'], 'Zend_Date') && is_string($n['category'])) : ?>
                <p class="pubDate"><?= Xmltv_String::ucfirst($n['pubDate']->toString(Zend_Date::WEEKDAY)) .' :: '. $this->escape($n['category']) ?></p>
            <?php endif; ?>
            
            <p class="title"><?= $vid['desc'] ?></p>
            
            <p class="description">
                <a href="<?= $href1 ?>" title="<?= $this->escape($n['title']) ?>">
                    <img src="<?= $thumb['url'] ?>" class="channelNewsImage" />
                </a><?= $n['desc'] ?>
            </p>
            
            <p class="link"><a href="<?= $href2 ?>" target="blank"<?= ($i<3) ? '' : ' rel="nofollow"' ; ?>>вся новость</a> > </p>
        </div>
            <?php
            $i++;
        }
        ?>
    </div>
        <?php
    }
    ?>
    
    <?php 
    //Top channels block
    if (isset($this->channelsTop) && !empty($this->channelsTop)) {
        ?>
    <div id="topChannels" class="module hidden-phone">
        <h4>Популярные каналы</h4>
        <ul>
            <?php 
            foreach ($this->channelsTop as $item){
                
                var_dump($item);
                die(__FILE__ . ': ' . __LINE__);
                
                $hrefUrl = $this->url( array(
                    'channel'=>$this->escape($item['channel_alias']), 
                    'date'=>  Zend_Date::now()->toString("dd-MM-YYYY")), 
                    'default_listings_day-date'
                );
            ?>
            <li>
                <img src="<?= $this->baseUrl( $this->escape($item['channel_icon']) ) ?>" />
                <a href="<?= $hrefUrl ?>"
                    title="«<?= $item['channel_title'] ?>» сегодня"">
                        <?= $this->escape($item['title']) ?>
                </a>
                <?php  ?>
            </li>
            <?php 	
            }
            ?>
        </ul>
    </div>	
        <?php 
    }
    ?>

</div>