<?php
/**
 * Right sidebar view script
 *
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: sidebar-right.phtml,v 1.12 2013-04-06 22:35:03 developer Exp $
 *
 */
?>

<?php
$this->inlineScript()->appendScript("$(document).ready(function(){ $('#rumor-ads').show(300); });");
?>
<div class="module" id="rumor-ads">
	<?php /*<h4 class="mediumheading">Желтая пресса</h4>*/ ?>
	<div class="content" id="DIV_DA_85753"></div>
</div>


<?php
if (count($this->videos) && $this->videos!==false) {
    
    $channelTitle = $this->escape($this->channel['title']);
	$this->headScript()->appendScript( Rtvg_Compressor_JSMin::minify("$(function() {
	var icons = { header: 'ui-icon-circle-arrow-e', activeHeader: 'ui-icon-circle-arrow-s' };
	$( '#col_r .videos_sidebar' ).accordion({
		header: 'h4',
		clearStyle: true,
		collapsible: true,
		active: 0,
		icons:{
			'header': 'ui-icon-plus',
			'headerSelected': 'ui-icon-minus',
		}
	}); });"));
	?>
	
	<div class="module">
	
		<h3 class="label">Онлайн-видео <?php echo $channelTitle ?></h3>
		
		<div class="videos_sidebar">
		<?php
		
		foreach ($this->videos as $video) {
			
		    $videoTitle = $this->escape( $this->truncateString( $video['title'], 32, 'letters' ));
		    $videoAlias = $this->escape( $video['alias'] );
		    $videoPublished = $video['published']->toString( 'd MMMM YYYY');
		    $videoDuration  = $video['duration']->toString( 'MM мин ss сек');
		    $videoDesc = $this->escape( $video['desc'] );
		    $linkTitle = empty($video['desc']) ? $videoTitle. $this->truncateString( $videoDesc, 40, 'letters') : $videoTitle ;
		    $linkHref = $this->url(array('alias'=>$videoAlias, 'id'=>$video['rtvg_id']), 'default_videos_show-video');
		    $thumb = $video['thumbs'][mt_rand( 0, count( $video['thumbs'])-1)];
		    
		    ?>
		    
			<h4><i class="icon-plus icon-white"></i><?php echo $videoTitle; ?></h4>
			
			<div class="info">
				
				<p class="viewcount">
					Понравилось <?php echo (int)$video['views']; ?> посетителям
				</p>
				
				<a href="<?php echo $linkHref; ?>" title="Клик чтобы смотреть видео <?php echo $linkTitle; ?>" target="_blank">
					<img src="<?php echo $thumb['url']; ?>" alt="<?php echo $linkTitle; ?>" />
				</a>
				
				<a class="btn btn-inverse btn-mini" href="<?php echo $linkHref; ?>" title="<?php echo $linkTitle; ?> видео" target="_blank">
					Смотреть
				</a>
				
				<div class="date">
					Загружено: <?php echo $videoPublished; ?>
				</div>
				
				<div class="duration">
					Длительность: <?php echo $videoDuration; ?>
				</div>
				
				<?php  if (!empty($video['desc'])): ?>
				<p class="desc">
					<?php
					$desc = $this->truncateString( $videoDesc, 30, 'words') ;
					if (stristr($desc, $this->channel['title'])) {
						$channelHref = '<a href="'.$this->url(array('channel'=>$this->channel['alias']), 'default_listings_day-listing') . '"
							target="_blank"
							title="Программа канала '.$this->channel['title'].'">'.$this->channel['title'].'</a>';
						echo Xmltv_String::str_ireplace($this->channel['title'], $channelHref, $desc);
					}
					echo $desc;
					?>
				</p>
				<?php endif; ?>
				
			</div>
		<?php
		
		}
		?>
			
	</div>
</div>
<?php
}
?>

<?php
if ($this->admitad === true){
    echo $this->adCode(array(
        'w'=>300,
        'h'=>300,
        'type'=>'cpa',
        'output'=>'stack',
        'amt'=>1,
    ));
}
?>

<div class="module">
	<h5 class="mediumheading">Телепрограмма vkontakte</h5>
	<div id="vk_groups"></div>
    <script type="text/javascript">
        VK.Widgets.Group("vk_groups", {mode: 0, width: "280", height: "320", color1: 'FFFFFF', color2: '000000', color3: '5B7FA6'}, 27716041);
    </script>
</div>

