<?php
/**
 * Left sidebar view script
 * 
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: sidebar-left.phtml,v 1.10 2013-03-08 04:06:13 developer Exp $
 *
 */
?>

<?php
/*
 * Channels categories block
 */ 
if (isset($this->cats) && !empty($this->cats)) {
    ?>
<div class="module">
	<?php /*<h4>Каналы</h4>*/ ?>
	<ul id="channels_categories" class="nav nav-list">
	<?php 
	foreach ($this->cats as $c) {
		$catAlias = $this->escape( $c['alias'] );
		$catTitle = $this->escape( Xmltv_String::ucfirst( Xmltv_String::strtolower( $c['title'] )));
		?>
		<li>
			<a href="<?php echo $this->url(array('category'=>$catAlias), 'default_channels_category' ) ?>" 
				title="<?php printf ("%s телеканалы", $catTitle) ?>"
				target="_blank">
				<img src="<?php echo $this->baseUrl( 'images/categories/channels/'.$this->escape( $c['image'] )); ?>" 
					class="icon" />
				<?php echo $catTitle ?>
			</a>
		</li>		
		<?php 
	}
	?>
	</ul>
</div>	
	<?php 
}
?>

<div class="module">
	<div style="width: 120px; margin: 0 auto; border: 1px solid #999;">
		<a target="_blank" rel="nofollow" href="http://ad.admitad.com/goto/b9685a874a43631d20753e1104d9e6/">
		<img width="120" height="600" border="0" src="http://ad.admitad.com/b/b9685a874a43631d20753e1104d9e6/" alt="Ренессанс Кредит" />
		</a>
	</div>
</div>

<?php 
/*
 * Top programs block
 */
if (isset($this->top_programs) && !empty($this->top_programs)) {
	?>
<div class="module">
	<h4>Популярные программы на этой неделе</h4>
	<ul id="program-top">
		<?php 
		foreach ($this->top_programs as $prog){
		    
		    if (APPLICATION_ENV=='development'){
			    //var_dump($prog);
			    //die(__FILE__.': '.__LINE__);
		    }
		    
		    ?>
		<li>
			<img src="<?php echo $this->baseUrl( 'images/channel_logo/'.$prog['channel_icon'] ) ?>" width="16" />
			<a href="<?php echo $this->url( array('channel'=>$prog['channel_alias'], 'alias'=>$prog['alias']), 'default_listings_program-week'); ?>"
				title="<?php echo $this->escape( sprintf("«%s» на канале %s на этой неделе", $prog['title'], $prog['channel_title'])) ?>"
				target="_blank"><?php echo $this->truncateString( $prog['title'], 3, 'words') ?>
			</a>
		</li>
			<?php 
			
		}
		?>
	</ul>
</div>	
	<?php 
}
?>


