<?php
/**
 * Week listing script for channel
 *
 * @uses Zend_Db_Table_Abstract
 * @version $Id: channel-week.phtml,v 1.10 2013-04-06 22:35:03 developer Exp $
 */

$this->headMeta()->setName('title', sprintf ('Программа телеканала «%s» на неделю c %s по %s ', $this->channel['title'], $this->week_start->toString('EEEE, d MMMM'), $this->week_end->toString('EEEE, d MMMM')));
$this->headMeta()->setName('keywords', sprintf ('телепрограмма,%s,неделя', strtolower( $this->channel['title'] )));

$this->headTitle( sprintf ('Программа телеканала «%s» на неделю с %s по %s', $this->channel['title'], $this->week_start->toString('d MMMM'), $this->week_end->toString('d MMMM yyyy')));

$channelAlias = $this->escape( $this->channel['alias'] );
$channelDesc  = $this->escape( $this->truncateString( $this->channel['desc_body'], 100, 'words' ));
?>

<h1>
	<?php printf( 'Программа канала «%s» на неделю', $this->channel['title'] ); ?>
</h1>

<p class="weekdate">
	<em><?php echo Xmltv_String::ucfirst( $this->week_start->toString('EEEE, d MMMM') ).' - '. Xmltv_String::ucfirst( $this->week_end->toString('EEEE, d MMMM') ); ?></em>
</p>

<?php if (!empty($channelDesc)): ?>
<p><?php echo $channelDesc; ?></p>
<?php endif; ?>



<a class="btn btn-mini btn-primary" href="<?php echo $this->url( array('channel'=>$channelAlias), 'default_listings_day-listing' ) ?>" 
	title="<?php printf( 'Программа %s на сегодня, %s', $this->channel['title'] , Zend_Date::now()->toString('EEEE, d MMMM yyyy')) ?>">
	<?php printf("Передачи канала «%s» сегодня", $this->channel['title']); ?>
</a>

<div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="button" data-yashareQuickServices="vkontakte,facebook,twitter,odnoklassniki,moimir,moikrug,gplus,surfingbird"></div>


<?php 
//var_dump($this->headStyle()->getContainer());
//die(__FILE__.': '.__LINE__);
$this->inlineScript()
	->prependScript("$(function(){
	$('#programlist').tabs({ collapsible: false });
});");
?>
<div class="week-list container-fluid" id="programlist">

	<ul class="nav nav-pills" id="days-tabs">
	<?php 
	$i=0;
	foreach ($this->days as $timestamp=>$programs) {
	    $date  = new Zend_Date($timestamp, "U");
		$dayId = $date->toString(Zend_Date::WEEKDAY_DIGIT);
		$class = Zend_Date::now()->toString('yyMMdd')==$date->toString('yyMMdd') ? "date active" : "date";
		?>
		<li class="<?php echo $class; ?>">
			<a href="<?php echo "#day$dayId" ?>" data-toggle="tab">
				<?php echo Xmltv_String::ucfirst($date->toString("EEEE")) ?>
			</a>
		</li>
		<?php 
		$i++;
	}
	?>
	</ul>
	
	<?php 
	foreach ($this->days as $timestamp=>$programs) {
	    $date = new Zend_Date( $timestamp, Zend_Date::TIMESTAMP );
	    $dayId = $date->toString(Zend_Date::WEEKDAY_DIGIT);
	    ?>
	    <table class="table day" id="<?php echo "day$dayId" ?>">
	    	<caption><?php echo Xmltv_String::ucfirst( $date->toString('EEEE, d MMMM yyyy')); ?></caption>
	    	<tbody>
	    		<?php foreach ($programs as $k=>$prog) {
	    		    $programTitle = $this->escape($prog['title']);
	    		    $programAlias = $this->escape($prog['alias']);
					$linkAttrHref = $this->url( array(
						'channel'=>$this->escape($this->channel['alias']),
						'alias'=>$programAlias), 'default_listings_program-week' 
					);
					$linkAttrTitle = sprintf("«%s на этой неделе»", $programTitle);
					?>
	    		<tr>
	    			<td><?php echo $prog['start']->toString("HH:mm"); ?></td>
	    			<td><a href="<?php echo $linkAttrHref ?>">
	    				<?php echo $programTitle; ?></a>
	    				<span class="label"><?php echo (isset($prog['category_title_single']) && !empty($prog['category_title_single'])) ? $prog['category_title_single'].' ' : '' ; ?></span>
	    			</td>
	    		</tr>
	    			<?php if (!empty($prog['desc'])) { ?>
	    			<tr>
	    				<td>&nbsp;</td>
	    				<td><?php echo $this->escape( $prog['desc'] ); ?></td>
	    			</tr>
	    			<?php
					} ?>
	    		<?php } ?>
	    	</tbody>
	    </table>
	    <?php 
	}
	?>
	
	</table>
</div>