<?php
/**
 * Week listing script for channel
 *
 * @uses Zend_Db_Table_Abstract
 * @version $Id: channel-week.phtml,v 1.6 2013-01-19 10:11:14 developer Exp $
 */
$this->headMeta()->setName('title', sprintf ('Программа телеканала «%s» на неделю c %s по %s ', $this->channel->title, $this->week_start->toString('EEEE, d MMMM'), $this->week_end->toString('EEEE, dd MMMM')));
$this->headTitle( sprintf ('Программа телеканала «%s» на неделю с %s по %s', $this->channel->title, $this->week_start->toString('dd MMMM'), $this->week_end->toString('dd MMMM yyyy')));
$this->headMeta()->setName('keywords', sprintf ('телепрограмма,%s,неделя', strtolower( $this->channel->title )));
$this->headScript()
	->appendFile($this->baseUrl()."/js/bootstrap-tab.js");
$css = '.nav-tabs > li > a { font-size: 0.8em; padding: 9px 6px; font-weight: bold; }
#programslist { border: none; }';
$this->headStyle()->appendStyle($css);
$channelAlias = $this->channel->alias;

?>

<h1>
	<?php printf( 'Программа канала «%s» на неделю', $this->channel->title ); ?>
</h1>

<p class="weekdate">
	<em><?php echo Xmltv_String::ucfirst( $this->week_start->toString('EEEE, dd MMMM') ).' - '. Xmltv_String::ucfirst( $this->week_end->toString('EEEE, dd MMMM') ); ?></em>
</p>

<a class="btn btn-mini btn-primary" href="<?php echo $this->url( array('channel'=>$channelAlias), 'default_listings_day-listing' ) ?>" 
	title="<?php printf( 'Программа %s на сегодня, %s', $this->channel->title , Zend_Date::now()->toString('EEEE, d MMMM yyyy')) ?>">
	Программы <?php printf("%s сегодня", $this->channel->title); ?>
</a>

<div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="button" data-yashareQuickServices="vkontakte,facebook,twitter,odnoklassniki,moimir,moikrug,gplus,surfingbird"></div>

<div class="week_list tabbable" id="programslist">
	<ul class="nav nav-tabs" id="days_tabs">
	<?php 
	$i=0;
	$tabsJs = "$(document).ready(function(){ \n";
	foreach ($this->days as $timestamp=>$programs) {
		$date = new Zend_Date($timestamp, "U");
		$dayId = $date->toString(Zend_Date::WEEKDAY_DIGIT);
		$class = Zend_Date::now()->toString('yyMMdd')==$date->toString('yyMMdd') ? "date active" : "date";
		$tabsJs .= '$("ul#days_tabs li a[href=\'#day'.$dayId.'\']").click(function (e) { e.preventDefault(); $(this).tab("show"); });';
		?>
		<li class="<?php echo $class; ?>">
			<a href="<?php echo "#day$dayId" ?>" data-toggle="tab">
				<?php echo Xmltv_String::ucfirst($date->toString("EEEE")) ?>
			</a>
		</li>
		<?php 
		$i++;
		//var_dump($list);
	}
	$tabsJs .='});';
	$this->headScript()->appendScript($tabsJs);
	?>
	</ul>
	
	<div class="tab-content">
	<?php
	$i=0;
	foreach ($this->days as $timestamp=>$programs) {
		$date = new Zend_Date($timestamp, Zend_Date::TIMESTAMP, 'ru');
		$day_id = $date->toString(Zend_Date::WEEKDAY_DIGIT);
		$class = Zend_Date::now()->toString('yyMMdd')==$date->toString('yyMMdd') ? 'tab-pane active fade in' : 'tab-pane fade';
		?>
		<div id="<?php echo "day$day_id" ?>" class="<?php echo $class; ?>">
		
		<h3>
			<?php echo Xmltv_String::ucfirst( $date->toString('EEEE, d MMMM yyyy')) ?>
		</h3>
		
		
		<?php 
		foreach ($programs as $k=>$prog) { 
			//var_dump($prog);
			?>
		<div class="item<?php echo $prog->start->toString('U'); ?> programdiv">
			<table class="table">
			
			<div class="program list">
				
				<p class="start">
					<span class="start_time"><?php echo $prog->start->toString('HH:mm') ?></span>
				</p>
				
				<div class="info">
					<h4>
						<a href="<?php echo $this->url( array('channel'=>$this->channel->alias, 'date'=>$date->toString('dd-MM-yyyy') ), 'default_listings_day-date' ); ?>">
							<?php echo $this->truncateProgramTitle($prog->title) ?>
						</a>
					</h4>
					
					<?php  if (!empty($prog->desc_intro)) : ?>
					<p class="desc">
						<?php echo $this->truncateString($prog->desc_intro, 15, 'words'); ?>
					</p>
					<?php endif;  ?>
					
				</div>
				
				<?php if (!empty($prog->sub_title)) : ?>
				<p class="subtitle"><?php echo $prog->sub_title ?></p>
				<?php endif; ?>
				
				<p class="end">
					<span class="end_time"><?php echo $prog->end->toString('HH:mm') ?></span>
				</p>
			</div>
			
			</table>
		</div>
		
		<?php 
		}
		$i++;
		?>
		</div>
		<?php 
	}
	?>
	</div>
</div>