<?php 
/**
 * View script for channel list
 * or channel category list
 * 
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: list.phtml,v 1.20 2013-04-03 18:18:05 developer Exp $
 *
 */

$categoryTitle = isset($this->category['title']) && !empty($this->category['title']) ? $this->escape( $this->category['title'] ) : null ;
$categoryAlias = isset($this->category['alias']) && !empty($this->category['alias']) ? $this->escape( $this->category['alias'] ) : null ;
$keywords = Xmltv_String::strtolower($categoryTitle) . ',' . Zend_Registry::get('site_config')->site->keywords;

if ($categoryTitle) {
	$this->headTitle( $categoryTitle.' телеканалы: передачи сегодня и на текущей неделе.' );
	$this->headMeta()
		->setName('title', $categoryTitle.' каналы передачи')
		->setName('description', $categoryTitle.' каналы с телепрограммой. Расписание передач на сегодня и на неделю.')
		->setName('keywords', $keywords );
} else {
	$this->headTitle( 'Программа всех каналов телевидения на сегодня и текущую неделю.' );
	$this->headMeta()
		->setName('title', 'Телепрограмма всех каналов')
		->setName('description', 'Все каналы с телепрограммой. Расписание передач на сегодня и на неделю.')
		->setName('keywords', $keywords );
}

$css = ".ui-autocomplete-category {
	font-weight: bold;
	padding: .2em .4em;
	margin: .8em 0 .2em;
	line-height: 1.5;
}";
$this->headStyle()->appendStyle($css);

$js = "$(function(){
    $('#channels').accordion({ icons:false, heightStyle:'content' });
});
";
$js = (APPLICATION_ENV=='production') ? Rtvg_Compressor_JSMin::minify($js) : $js ;
$this->headScript()->appendScript( $js );
?>

<div class="row-fluid">
    <?php
    if ($this->category) {
        echo '<h1>'.$categoryTitle.'</h1>';
        //printf('<p class="label label-info">Телеканалы в категории «%s»: %d</p>', $categoryTitle, count($this->channels)) ;
    } else {
        //Scroll to channel (with autocomplete)
        /*echo new Xmltv_Form_TypeaheadForm( array(
            'method'   => 'post',
            'enctype'  => 'application/x-www-form-urlencoded',
            'name'     => 'typeahead',
            'id'       => 'typeahead',
            'html_tag' => array( 
                'tag'   => 'div',
                'class' => 'container-fluid'
            ),
            'input'    => array( 
                'style' => 'width:100%;',
                'label' => 'Быстрый поиск канала',
                'id'    => 'searchinput',
                'html_tag' => array(
                    'tag'=>'div'
                )
            ),
            'append'   => '#content',
            'scroll'   => false,
        ));*/
        echo '<h1>Все каналы на Rutvgid</h1>';
    } ?>
</div>


<div class="row-fluid" id="shareCode">
    <?php echo $this->shareCode ?>
</div>

<div id="channels" class="row-fluid">
    
    <?php
    foreach ($this->channels as $channel) { 
        
        $id = (int)$channel['id'];
        $alias = $this->escape($channel['alias']);
        $title = $this->escape($channel['title']);
        $logo = $this->baseUrl($this->escape($channel['icon']));
        ?>
	
	<h3 class="channeltitle" id="#channeltitle<?php echo $id ?>">
		<img class="channelicon" 
			width="40" 
			src="<?php echo $logo; ?>" 
			alt="<?php printf('%s', Xmltv_String::strtolower($title)) ?>" />
		<?php echo $channel['title'] ?>
	</h3>
	
	<div class="channeldesc">
        
        <div class="span12">
            <?php 
            if ((int)$channel['torrenttv_id']>0 || $channel['tvforsite_id']){ 
                ?>
            <a href="<?php echo $this->url(array('channel'=>$alias), 'default_channels_live'); ?>"
               class="btn btn-small btn-info linkLive">Онлайн</a>
            <?php } ?>

            <a class="btn btn-small" 
                href="<?php echo $this->url(array('channel'=>$alias), "default_listings_day-listing"); ?>" 
                title="<?php printf('%s сегодня', $title) ?>"
                target="_blank">
                Передачи сегодня
            </a>

            <a class="btn btn-small" 
                href="<?php echo $this->url(array('channel'=>$alias), "default_channels_channel-week"); ?>" 
                title="<?php printf('%s на неделю', $channel['title']) ?>">
                Неделя
            </a>
        </div>
        
        <p class="span12">
			<?php echo $this->escape( $channel['desc_intro'] ) ?>
		</p>
        
	</div>

	<?php 
	}
	?>
</div>
