<?php 
/**
 * View script for channel list
 * or channel category list
 * 
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: list.phtml,v 1.20 2013-04-03 18:18:05 developer Exp $
 *
 */

$categoryTitle = isset($this->category['title']) && !empty($this->category['title']) ? $this->escape( $this->category['title'] ) : null ;
$categoryAlias = isset($this->category['alias']) && !empty($this->category['alias']) ? $this->escape( $this->category['alias'] ) : null ;
$keywords = Xmltv_String::strtolower($categoryTitle) . ',' . Zend_Registry::get('site_config')->site->get('keywords', 'телепрограмма,каналы,программа тв,каналы,телеканалы,каналы тв');

if ($categoryTitle) {
	$this->headTitle( $categoryTitle.' телеканалы: передачи сегодня и на текущей неделе.' );
	$this->headMeta()
		->setName('title', $categoryTitle.' каналы передачи')
		->setName('description', $categoryTitle.' каналы с телепрограммой. Расписание передач на сегодня и на неделю.')
		->setName('keywords', $keywords );
} else {
	$this->headTitle( 'Программа всех каналов телевидения на сегодня и текущую неделю.' );
	$this->headMeta()
		->setName('title', 'Телепрограмма всех каналов')
		->setName('description', 'Все каналы с телепрограммой. Расписание передач на сегодня и на неделю.')
		->setName('keywords', $keywords );
}

$css = ".ui-autocomplete-category {
	font-weight: bold;
	padding: .2em .4em;
	margin: .8em 0 .2em;
	line-height: 1.5;
}";
$this->headStyle()->appendStyle($css);

$js = "$(function(){
$('#channels').accordion({ icons:false, heightStyle:'content' });
});
";
$js = (APPLICATION_ENV=='production') ? Rtvg_Compressor_JSMin::minify($js) : $js ;
$this->headScript()->appendScript( $js );
?>

<h2>Передачи сегодня и на неделе</h2>
	
<?php 
if ( isset($this->category) && $this->category!==null) {
	echo '<h1>'.$categoryTitle.' каналы'.'</h1>';
	printf('<p class="label label-info">Телеканалы в категории «%s»: %d</p>', $categoryTitle, count($this->channels)) ;
} ?>

<h1>Все каналы</h1>

<div id="channels">

	<?php
	foreach ($this->channels as $channel) { 
		$id	= $channel['id'];
		$title = $channel['title'];
		$alias = $channel['alias'];
		$icon  = $channel['icon'];
		?>
	
	<h3 class="channeltitle" id="#channeltitle<?php echo $id ?>">
		<img class="channelicon" 
			width="40" 
			src="<?php echo $icon; ?>" 
			alt="<?php printf('%s лого', Xmltv_String::strtolower($title)) ?>" />
		<?php echo $channel['title'] ?>
	</h3>
	
	<div class="channeldesc">
		<a class="label" 
			href="<?= $this->url(array('channel'=>Xmltv_String::strtolower($alias)), "default_listings_day-listing"); ?>" 
			title="<?php printf('Телепрограмма %s на сегодня', $title) ?>"
			target="_blank">
			<?php printf('«%s» сегодня', $channel['title']) ?>
		</a>
		<a class="label label-info" 
			href="<?= $this->url(array('channel'=>Xmltv_String::strtolower($alias)), "default_channels_channel-week"); ?>" 
			title="<?php printf('Телепрограмма %s на неделю', $channel['title']) ?>">
			Программа на неделю
		</a>
		
		<p>
			<?php echo $this->escape( strip_tags($channel['desc_intro']) ) ?>
		</p>
		<p>
			<?php echo $this->truncateString( strip_tags($channel['desc_body']), 40, 'words'); ?>
		</p>
	</div>

	<?php 
	}
	?>
</div>
