<?php
/**
 * Add new comments to page with AJAX
 * 
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: new-comments.ajax.phtml,v 1.4 2013-04-03 04:08:16 developer Exp $
 *
 */


if(APPLICATION_ENV=='development'){
    //var_dump($this->items);
    //die(__FILE__.': '.__LINE__);
}

if (isset($this->items) && count($this->items) && $this->items!==false){
	foreach ($this->items as $comment) {
	    
	    if(APPLICATION_ENV=='development'){
			//var_dump($comment);
	        //die(__FILE__.': '.__LINE__);
	    }
	    
		?>
		
	<div>
	
		<?php if (!empty($comment['title'])) : ?>
		<div class="summary"><?php echo $comment['title'] ?></div>
		<?php else: ?>
		<div class="summary">
			<?php echo $this->escape( $this->channel->title ); ?>
		</div>
		<?php endif; ?>
		
		
		<?php if (!empty($comment['author'])) : ?>
		<div class="author">
			<a href="<?php echo $comment['link'] ?>" rel="nofollow" target="_blank">
				<small><?php echo $comment['author'] ?></small>
			</a>
		</div>
		<?php endif; ?>
		
		
		<?php if (!empty($comment['date_created'])) { ?>
		<div class="date">
			<?php echo $comment['date_created']->toString('EEEE, dd MMM yyyy hh:mm'); ?>
		</div>
		<?php 
		} ?>
		
		
		<div class="description">
			<?php echo str_ireplace($this->channel->title, '<em>'.$this->channel->title.'</em>', $comment['intro']) ?>
		</div>
		
		
	</div>
		<?php 
	}
	?>


<?php  
} ?>