<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

	<url>
      <loc>http://rutvgid.ru/</loc>
      <lastmod>2005-01-01</lastmod>
      <changefreq>monthly</changefreq>
      <priority>0.8</priority>
   </url>
   
   <?php 
	//var_dump($this->channel_aliases);
	//die(__FILE__.': '.__LINE__);
	foreach ($this->channel_aliases as $i) {
		?>
		<url>
			<loc>http://rutvgid.ru/телепрограмма/<?php echo $i ?></loc>
			<lastmod><?php echo $this->week_start ?></lastmod>
		    <changefreq>weekly</changefreq>
		    <priority>1</priority>
		</url>
		<?php 
	}
   ?>
	
</urlset>
