<?php 
echo '<?xml version="1.0" encoding="UTF-8"?>'; 
$weekStart = $this->week_start->toString('YYYY-MM-dd');
?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<url>
		<loc>http://rutvgid.ru<?php echo $this->baseUrl(); ?></loc>
        <lastmod><?php echo Zend_Date::now()->subHour(6)->toString("YYYY-MM-dd") ?></lastmod>
		<changefreq>always</changefreq>
		<priority>1</priority>
	</url>
	<url>
      <loc>http://rutvgid.ru<?php echo $this->url( array(), 'default_channels_list'); ?></loc>
      <lastmod><?php echo Zend_Date::now()->subDay(7)->toString("YYYY-MM-dd") ?></lastmod>
      <changefreq>weekly</changefreq>
      <priority>1</priority>
   </url>
<?php 
foreach ($this->channel_aliases as $a) {
    $alias  = $this->escape($a);
    $dayUrl = $this->url( array(
    	'channel'=>$alias), 'default_listings_day-listing');
    $weekUrl = $this->url( array(
    	'channel'=>$alias), 'default_channels_channel-week');
    ?>
	<url>
		<loc>http://rutvgid.ru<?php echo $dayUrl; ?></loc>
		<lastmod><?php echo $weekStart ?></lastmod>
	    <changefreq>daily</changefreq>
	    <priority>1</priority>
	</url>
	<url>
		<loc>http://rutvgid.ru<?php echo $weekUrl; ?></loc>
		<lastmod><?php echo $weekStart ?></lastmod>
	    <changefreq>weekly</changefreq>
	    <priority>1</priority>
	</url>
<?php 
} ?>
 
<?php
foreach ($this->week_items as $i){
	$url = $this->url( array(
    	'channel'=>$i['channel_alias'],
    	'alias'=>$i['alias'] ), 'default_listings_broadcast-week');
	if ( strlen($url)<=254 ) {
    ?>
    <url>
		<loc>http://rutvgid.ru<?php echo $url; ?></loc>
		<lastmod><?php echo $weekStart ?></lastmod>
	    <changefreq>weekly</changefreq>
	    <priority>0.5</priority>
	</url>
    <?php 
	}
}
?>
</urlset>
