<?php 
/**
 * Frontpage view script
 * 
 * @author  Antony Repin
 * @version $Id: index.phtml,v 1.11 2013-04-06 22:35:04 developer Exp $
 *
 */

$this->headTitle( 'Программа всех каналов телевидения на сегодня и текущую неделю.' );

$this->headMeta()
	->setName( 'keywords', Zend_Registry::get('site_config')->site->get('keywords', 'телепрограмма,каналы,программа тв,каналы,телеканалы,каналы тв') )
	->setName( 'description', Zend_Registry::get('site_config')->site->get('description', 'Программа всех каналов телевидения на сегодня и текущую неделю.') );

$js = '$(document).ready(function($){
	$("#channel").change(function(e){
		var selected = $("#channel :selected").val();
		var text = $("#channel :selected").html();
		var newDiv = $("<div/>");
		var otherDivs = $("#listing .channel");
		newDiv.attr({ 
			"id":"new"+selected,
			"class":"channel",
			"style":"min-height:90px;vertical-align:middle;",
		});
		newDiv.hide().html("<h2 class=\"title\">Загружаю передачи для &laquo;"+text+"&raquo;, немного подожите&hellip;</h2>").show(300);
		$("#listing").prepend(newDiv);
		$.get( "'.$this->baseUrl('frontpage/single-channel/format/html/id/').'"+selected, function(respHtml) {
			newDiv.html(respHtml);
			$(newDiv).hide().show(800);
			otherDivs.each(function(){
				$(this).css({ opacity: 0.6 });
			});
			
		});
	});
});';
$js = (APPLICATION_ENV=='production') ? Rtvg_Compressor_JSMin::minify( $js ) : $js ;
$this->inlineScript()->appendScript( $js );

?>

<div class="page">
	
	<div id="news" class="row-fluid">
		<?php 
		foreach ($this->articles as $article){
		    $w = floor(12/$this->articles_amt);
		    $linkAttrHref = $this->url( array( 
		    	'category_id'=>$article['content_cat_id'],
		    	'article_alias'=>$this->escape($article['alias'])), 'default_content_article' );
		    ?>
		    <div class="span<?php echo $w; ?> announce">
		    	<img width="42" height="42" src="/images/icons/article-image-default.png" border="0" />
		    	<a href="<?php echo $linkAttrHref; ?>"
		    		title="<?php echo $article['metadesc']; ?>"
		    		target="_blank">
		    		<?php echo $this->escape($article['title']); ?>
		    	</a>
		    </div>
		    <?php 
		}
		?>
	</div>
	
	<div class="row-fluid" style="margin: 10px 0;"><?php
	$dropdown = new Zend_Form_Element_Select('channel');
	$options  = array();
	foreach ($this->channels as $k=>$c){
	    $options[$k] = array('key'=>(int)$c['id'], 'value'=>$c['title']);
	}
	$dropdown->setMultiOptions($options);
	$dropdown->setAttribs( array(
		'name'=>'channelselect',
		'size'=>1,
		))
		->setLabel("Передачи сейчас на канале")
		->setDecorators(array(
			'ViewHelper',
			'Errors',
			array( 'HtmlTag', array( 'tag'=>'div', 'class'=>'select-container' ) ),
			'Label',
		));
	echo $dropdown;
	?>
		<h1><a href="<?php echo $this->url(array(), 'default_channels_list'); ?>">Все каналы</a></h1>
	</div>
	
	<div id="gcse-results" style="width: 640px; margin: 0 auto;">
		<gcse:searchbox></gcse:searchbox>
		<gcse:searchresults></gcse:searchresults>
	</div>	
	
	<div id="listing">
	<?php 
	$max=4;
	foreach ($this->list as $channel){
	    
	    $keys = array_keys($channel);
	    $channelHash = hash( 'crc32', $channel[$keys[0]]['channel'] );
	    $dayLinkAttrHref = $this->url( array(
	    			'channel'=>$this->escape($channel[$keys[0]]['channel_alias'])), 'default_listings_day-listing');
	    $dayLinkAttrTitle = $this->escape( sprintf("Передачи «%s» сегодня", $this->escape($channel[$keys[0]]['channel_title'])));
	    $dayLinkText = $this->escape( sprintf("«%s» сегодня", $channel[$keys[0]]['channel_title']));
	    $weekLinkAttrHref = $this->url( array(
	    			'channel'=>$this->escape($channel[$keys[0]]['channel_alias'])), 'default_channels_channel-week');
	    $weekLinkAttrTitle = $this->escape( sprintf("Передачи «%s» на этой неделе", $this->escape($channel[$keys[0]]['channel_title'])));
	    $weekLinkText =  $this->escape( sprintf("«%s» расписание на неделю" , $channel[$keys[0]]['channel_title']));
	    ?>
	    <div class="channel" id="<?php echo $channelHash ?>">
	    	<h3 class="title"><a href="<?php echo $weekLinkAttrHref ?>" target="_blank" title="<?php echo $weekLinkAttrTitle ?>"><?php echo $weekLinkText; ?></a></h3>
	    	<h2 class="title"><a href="<?php echo $dayLinkAttrHref ?>" target="_blank" title="<?php echo $dayLinkAttrTitle ?>"><?php echo $dayLinkText ?></a></h2>
	    	<div class="progs">
	    <?php 
	    $w = count($channel)>$max ? floor((100-$max)/$max) : floor((100-count($channel))/count($channel));
	    $c = 0;
	    foreach ($channel as $prog){
	        $showRating = false;
	        if ($c<$max){
	            $timespan = '';
	            switch ($c){
	            	case 0:
	            	    $timespan = 'Сейчас';
	            	    $bg = "#FFCC00";
	            	    $showRating = true;
	            	    break;
	            	case 1:
	            	    $timespan = 'Далее';
	            	    $bg = "#BABABA";
	            	    $showRating = true;
	            	    break;
	            	case 2:
	            	    $timespan = 'Затем';
	            	    $bg = "#FFFFFF";
	            	    $showRating = true;
	            	    break;
	            	case 3:
	            	    $timespan = 'После';
	            	    $bg = "#FFFFFF";
	            	    break;
	            	default: break;
	            }
		        ?>
		    
	        <div class="item" style="width:<?php echo $w."%" ?>;">
	        
	        	<div class="time" style="background-color: <?php echo $bg ?>;">
	        		<?php echo $timespan ?>
	        	</div>
	        	
	        	<div class="info">
	        	
	        		<p>
	        			<?php $text = $timespan=='Сейчас' ? '' : 'Начало в '  ; ?>
	        			<?php echo $text ?><strong><?php echo $prog['start']->toString("HH:mm") ?></strong>
	        		</p>
	        		
	        		<p class="title">
		        		<a href="<?php echo $this->url( array(
		        		'channel'=>$this->escape($prog['channel_alias']),
		        		'alias'=>$this->escape($prog['alias']) ), 'default_listings_broadcast-week') ?>"
		        		title="<?php echo $this->escape(sprintf("Программа «%s» на неделе", $this->escape($prog['title']))) ?>">
		        			<?php echo $this->escape( $prog['title'] ) ?>
		        		</a>
	        		</p>
	        		
	        		<?php if (!empty($prog['sub_title'])): ?>
	        		<p class="sub_title">
	        			<?php echo $this->escape( $prog['sub_title'] ) ?>
	        		</p>
	        		<?php endif; ?>
	        		
	        		<a href="<?php echo $this->url( array('category'=>$this->escape( $prog['category_alias'] ), 'timespan'=>'сегодня'), 'default_listings_category' ) ?>"
		        		title="<?php printf("Все %s на канале «%s» сегодня", 
		        			Xmltv_String::strtolower( $this->escape( $prog['category_title'] )),
		        			$this->escape( $prog['channel_title'] )) ?>">
		        		<?php echo $this->escape( $prog['category_single'] ) ?>
		        	</a>
		        	<br />
		        	<?php if ((int)@$prog['rating']>0 && $showRating===true): ?>
		        	<span class="rating">Возрастной рейтинг: <?php echo $this->escape( $prog['rating'] ).'+' ?></span>
		        	<?php endif; ?>
	        	</div>
	        	
	        </div>
		        <?php 
		        $c++;
	        }
	    }
	    ?>
	    	</div>
	    </div>
	    <?php 
	}
	?>
	</div>
	
</div>




