<?php 
/**
 * Frontpage view script
 * 
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: index.phtml,v 1.3 2013-02-15 00:44:02 developer Exp $
 *
 */

$this->headTitle( 'Программа всех каналов телевидения на сегодня и текущую неделю.' );
$this->headMeta()
	->setName( 'keywords', Zend_Registry::get('site_config')->site->get('keywords', 'телепрограмма,каналы,программа тв,каналы,телеканалы,каналы тв') )
	->appendName( 'description', Zend_Registry::get('site_config')->site->get('description', 'Программа всех каналов телевидения на сегодня и текущую неделю.') );

?>

<div class="page">
	
	<div class="sitesearch">
		<gcse:searchbox></gcse:searchbox>
	</div>
	
	<div id="listing">
	<?php 
	$max=4;
	foreach ($this->list as $channel){
	    $keys = array_keys($channel);
	    ?>
	    <div class="channel" id="<?php echo hash( 'crc32', $channel[$keys[0]]['channel'] ) ?>">
	    	<h3 class="title">
	    		<a href="<?php echo $this->url( array(
	    			'channel'=>$this->escape($channel[$keys[0]]['channel_alias'])), 'default_listings_day-listing') ?>"
	    			target="_blank" 
	    			title="<?php echo $this->escape( sprintf("Передачи «%s» сегодня", $this->escape($channel[$keys[0]]['channel_title']))) ?>">
	    				<?php echo $this->escape( sprintf("%s сегодня", $channel[$keys[0]]['channel_title'])) ?>
	    		</a>
	    	</h3>
	    	<div class="progs">
	    <?php 
	    $w = count($channel)>$max ? floor((100-$max)/$max) : floor((100-count($channel))/count($channel));
	    $c = 0;
	    foreach ($channel as $prog){
	        $showRating = false;
	        if ($c<$max){
	            $timespan = '';
	            switch ($c){
	            	case 0:
	            	    $timespan = 'Сейчас';
	            	    $bg = "#FFCC00";
	            	    $showRating = true;
	            	    break;
	            	case 1:
	            	    $timespan = 'Далее';
	            	    $bg = "#BABABA";
	            	    $showRating = true;
	            	    break;
	            	case 2:
	            	    $timespan = 'Затем';
	            	    $bg = "#FFFFFF";
	            	    $showRating = true;
	            	    break;
	            	case 3:
	            	    $timespan = 'После';
	            	    $bg = "#FFFFFF";
	            	    break;
	            	default: break;
	            }
		        ?>
		    
	        <div class="item" style="width:<?php echo $w."%" ?>;">
	        
	        	<div class="time" style="background-color: <?php echo $bg ?>;">
	        		<?php echo $timespan ?>
	        	</div>
	        	
	        	<div class="info">
	        	
	        		<p>
	        			<?php $text = $timespan=='Сейчас' ? '' : 'Начало в '  ; ?>
	        			<?php echo $text ?><strong><?php echo $prog['start']->toString("HH:mm") ?></strong>
	        		</p>
	        		
	        		<h4 class="title">
		        		<a href="<?php echo $this->url( array(
		        		'channel'=>$this->escape($prog['channel_alias']),
		        		'alias'=>$this->escape($prog['alias']) ), 'default_listings_program-week') ?>"
		        		title="<?php echo $this->escape(sprintf("Программа «%s» на неделе", $this->escape($prog['title']))) ?>">
		        			<?php echo $this->escape( $prog['title'] ) ?>
		        		</a>
	        		</h4>
	        		
	        		<?php if (!empty($prog['sub_title'])): ?>
	        		<p class="sub_title">
	        			<?php echo $this->escape( $prog['sub_title'] ) ?>
	        		</p>
	        		<?php endif; ?>
	        		
	        		<a href="<?php echo $this->url( array('category'=>$this->escape( $prog['category_alias'] ), 'timespan'=>'сегодня'), 'deault_listings_category' ) ?>"
		        		title="<?php printf("Все %s на канале «%s» сегодня", 
		        			Xmltv_String::strtolower( $this->escape( $prog['category_title'] )),
		        			$this->escape( $prog['channel_title'] )) ?>">
		        		<?php echo $this->escape( $prog['category_single'] ) ?>
		        	</a>
		        	<br />
		        	<?php if ((int)$prog['rating']>0 && $showRating===true): ?>
		        	<span class="rating">Возрастной рейтинг: <?php echo $this->escape( $prog['rating'] ).'+' ?></span>
		        	<?php endif; ?>
	        	</div>
	        	
	        </div>
		        <?php 
		        $c++;
	        }
	    }
	    ?>
	    	</div>
	    </div>
	    <?php 
	}
	?>
	</div>
	
</div>




