<?php
/**
 * Wiew script for programs category listing day
 * 
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: category-day.phtml,v 1.2 2013-03-01 03:49:38 developer Exp $
 *
 */
$this->headTitle( $this->category['title']." ".$this->today->toString("d MMMM YYYY"));
$this->headMeta( $this->category['title'], "description");
?>

<h1>
	<?php printf( "%s сегодня", $this->category['title']); ?>
</h1>

<p>
	<?php printf("Сегодня %d программ", count($this->list)); ?>
</p>

<?php 
foreach ($this->list as $single){
    ?>
    <div class="item programcontainer">
    	<p>
			<span class="label label-warning"><?php echo Xmltv_String::ucfirst( $single['start']->toString( 'EEEE')); ?></span>&nbsp;
			<u><?php echo $single['start']->toString( 'HH:mm') ?></u>
			<?php echo $single['category_title_single'] ?> 
				<a href="<?php echo $this->url( array('channel'=>$single['channel_alias'], 'date'=>$single['start']->toString("dd-MM-yyyy")), 'default_listings_day-date' ).'?ts='.$single['start']->toString("U") ?>"
					title="<?php echo $single['title'] ?> <?php echo $single['start']->toString( 'dd MMM') ?> на канале <?php echo $single['channel_title'] ?>"
					target="_blank">
					<em><?php echo $single['title'] ?></em>
			</a> на канале <b><?php echo $single['channel_title'] ?></b>
			<?php //echo (bool)$single['live']==-true ? 'в прямом эфире' : '' ; ?>
			<?php //echo (bool)$single['premiere']===true ? '. Премьера!' : '' ; ?>
			
		</p>
    </div>
    <?php 
}
?>