<?php 
/**
 * Day listing script for channel
 * 
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: day-listing.phtml,v 1.15 2013-01-12 09:06:22 developer Exp $
 *
 */

$channelTitle = $this->escape($this->channel->title);
$channelAlias = $this->escape($this->channel->alias);


$this->headScript()
	->appendFile($this->baseUrl()."/js/listing-day.js")
	->appendScript("$('.top-position img').tooltip({ showURL: false });
	$('.carousel').carousel('pause');
	$(document).ready(function($){
		$.ajax({ url: '/channels/new-comments/channel/".$this->escape($this->channel->alias)."/format/html',
			dataType: 'html', success: function(html){ $(html).insertAfter($('#comments h3')); }
		});
	});
");


/*
 * Generate keywords
 */
$kw = array($channelTitle, $this->listing_date->toString('d MMMM YYYY'));
if (!empty($this->programs)) {
	foreach ($this->programs as $p) {
		if (count($kw)<5) {
			if (!in_array($p->title, $kw))
			$kw[]= Xmltv_String::strtolower( htmlspecialchars( $p->title, ENT_QUOTES, 'utf-8' ) );
		}
	}
}
$this->headMeta()->setName('keywords', implode(',', $kw) );


if ($this->is_today) {
    $this->headScript()
    ->appendScript("$('a#carousel_onoff').click(function(){
    		_gaq.push(['_trackPageview', '".$this->url( array('channel'=>$channelAlias), 'default_listings_day-listing')."']);
    });");
	//META title
	$this->headMeta()->setName('title', sprintf ('Программа телеканала %s на сегодня, %s. Видео записей программ.', $channelTitle, $this->listing_date->toString( 'EEEE, d MMMM YYYY' )));
	//Browser window title
	$this->headTitle( sprintf ('Телепрограмма %s на сегодня', $channelTitle ) );
} else {
    $this->headScript()
    ->appendScript("$('a#carousel_onoff').click(function(){
    		_gaq.push(['_trackPageview', '".$this->url(array('channel'=>$channelAlias, 'date'=>$this->listing_date->toString('dd-MM-yyyy')), 'default_listings_day-date')."']);
    });");
	//META title
	$this->headMeta()->setName('title', sprintf ('Программа канала %s за %s. Видео записей программ.', $channelTitle, $this->listing_date->toString('EEEE, d MMMM YYYY')));
	//Browser window title
	$this->headTitle( sprintf ('Телепрограмма %s за %s', $channelTitle, $this->listing_date->toString( 'EEEE, d MMMM YYYY' ) ) );
}

?>

<div class="top-position">
	<div class="module" style="float: left; width: 68%;">
		<?php 
		$tip = "Начните вводить название канала и выберите его из списка. Окно браузера автоматически переместится к выбранному каналу.";
		if ($this->category) {
		  $tip .=" Если канала нет в категории <i>".$this->category['title']."</i>, наберите его название или часть названия и нажмите Перейти.";  
		} 
		?>
		<img class="tip" src="/images/icons/tip-12x12.png" title="<?php echo $tip ?>" />
		<?php echo new Xmltv_Form_TypeaheadForm(); ?>
	</div>
	<div class="module" style="width: 30%; float: right;">
		<?php echo new Xmltv_Form_TimezoneSwitch(array('label_class'=>'smallheading', 'time_shift'=>$this->timeshift)); ?>
	</div>
</div>

<h1>
	<?php
	if ($this->is_today){
		printf('Программа «%s» сегодня', $channelTitle); 
	} else {
		printf('Программа «%s» %s', $channelTitle, $this->listing_date->toString('d MMMM YYYY'));
	}?>
</h1>

<?php if ($this->is_today) : ?>
<strong><?php echo Xmltv_String::ucfirst( $this->listing_date->toString("EEEE, d MMMM YYYY") ); ?></strong>
<?php endif; ?>


<div class="module ad468">
	<?php /*<script type="text/javascript" src="http://www.adcash.com/script/java.php?option=rotateur&rotateur=106375"></script>*/ ?>
	<script type="text/javascript" src="http://c.am11.ru/code/bn/js.php?u=13073&f=5"></script>
</div>


<?php
/*
 * Programs list
 */ 
if (!empty($this->programs)) {
	?>
	
<a class="btn btn-info" id="carousel_onoff" href="#" title="Отобразить расписание в виде списка и перейти к текущей передаче">Показать расписание списком</a>
	
<div id="programslist" class="carousel slide">
	<div class="carousel-inner" id="programs-carousel">
	<?php 
	foreach ($this->programs as $k=>$prog) {
		
		//var_dump($prog);
		if ($this->is_today) {
			$active = $prog->now_showing===true ? ' active' : '' ;
		} else {
			$active = $k==0 ? ' active' : '' ;
		}
		?>
	<div class="item<?php echo $active; ?> programcontainer">
		
		<div class="program-times">
			<div class="time start">
				<span class="label label-important"><?php echo $prog->start->toString('HH:mm') ?></span>
			</div>
			<div class="time end">
				<span class="label label-important"><?php echo $prog->end->toString('HH:mm') ?></span>
			</div>
		</div>
		
		<?php  if ($active==' active') : ?>
		<p class="label label-warning">
			Сейчас в эфире
		</p>
		<?php endif; ?>
		
		<?php if ($prog->live): ?>
		<img src="<?php echo $this->baseUrl('images/icons/live.png'); ?>" />
		<?php endif; ?>
		
		<div class="programtitle">
			<h3>
				<a href="<?php echo $this->url( array(
					'channel'=>$this->channel->alias,
					'alias'=>$prog->alias), 'default_listings_program-week' ); ?>"
					title="Расписание <?php echo $prog->title ?> на неделю"
					target="_blank">
					<?php echo $prog->title; ?>
				</a>
			</h3>
			
			<?php if (!empty($prog->sub_title)) : ?>
			<p class="subtitle"><?php echo $prog->sub_title ?></p>
			<?php endif; ?>
			
		</div>
		
		
		<?php if (isset($prog->category_title) && !empty($prog->category_title)): ?>
		<div class="category">
			<a href="<?php echo $this->url( array(
				'category'=>$prog->category_alias,
				'timespan'=>'неделя'), 'deault_listings_category'); ?>" title="Передачи на неделе">
				<?php echo $prog->category_title; ?> на этой неделе
			</a>
			<a href="<?php echo $this->url( array(
				'category'=>$prog->category_alias,
				'timespan'=>'сегодня'), 'deault_listings_category'); ?>" title="Передачи сегодня">
				<?php echo $prog->category_title; ?> сегодня
			</a>
		</div>
		<?php endif; ?>
		
		
		<?php if (isset($prog->rating) && $prog->rating>0) : ?>
		<p class="rating">Возрастной рейтинг: 
			<span class="label label-warning"><?php echo $prog->rating ?>+</span>
		</p>
		<?php endif; ?>
		
		<?php /*
		<p>
			<a class="btn btn-mini btn-primary" title="Скачать <?php echo $prog->title ?>" href="<?php echo $this->url(array(), 'default_torrents_finder') ?>?s=<?php echo urlencode(strrev(base64_encode($prog->title))); ?>">
				Скачать <?php echo $prog->title ?>
			</a>
		</p>
		*/ ?>
		
		
		<?php 
		/*
		 * Описание программы
		 */
		if (!empty($prog->desc_intro)) { 
			?>
		<p class="video-desc">
			<?php echo $this->truncateString( $prog->desc_intro, 100, 'words' ) ?>
		</p>
			<?php
		}
		
		if (!empty($prog->desc_body)) { 
			?>
		<p class="desc body">
			<?php echo $this->truncateString( $prog->desc_body, 100, 'words' ) ?>
		</p>
			<?php 
		} 
		?>
		
		
		<?php 
		/*
		 * Видео
		 */
		if ( count($this->listing_videos)) {
			if ( array_key_exists( $prog->hash, $this->listing_videos) && !empty($this->listing_videos[$prog->hash])){
				
				$vid = $this->listing_videos[$prog->hash];
				
				?>
				
				<div class="program-video">
				<?php 
				$videoTitle = $this->escape( $vid->title );
				$videoAlias = $this->escape( $vid->alias );
				$videoDesc  = $this->escape( $vid->desc );
				$videoId	= $vid->rtvg_id;
				$videoUrl = $this->url(array('alias'=>$videoAlias, 'id'=>$videoId), 'default_videos_show-video');
				?>
				
				<?php 
				if ($thumbs = $vid->thumbs){
					$wrapStyle = empty($videoDesc) ? 'width: 100%;' : 'float:left; width:120px; margin: 0 1em 0.25em 0;' ;
					?>
				<div style="<?php echo $wrapStyle ?>" itemscope itemtype="http://schema.org/ImageObject"> 
					<?php 
					foreach ($thumbs as $thumb){
						$thW = (int)Zend_Registry::get('site_config')->videos->listing->get('thumb_width', 240);
						?>
						<a href="<?php echo $videoUrl ?>"
							title="Видео, похожие на <?php echo $videoTitle ?>">
							<img src="<?php echo $thumb->url ?>" width="<?php echo $thW ?>" alt="<?php echo $videoTitle ?>" />
						</a>
						<?php 
					}
					?>
				</div>
					<?php 
				}
				?>
				
				<h4 class="title">
					<?php //$vlink = empty($videoDesc) ? $videoTitle.$this->truncateString( $videoDesc, 40, 'letters') : $videoTitle; ?>
					<?php //echo $vlink ?>
					<?php echo $videoTitle ?>
				</h4>
				
				<a class="btn btn-mini" href="<?php echo $videoUrl; ?>" 
					title="Видео <?php echo $videoTitle; ?>">
					Смотреть онлайн
				</a>
				
				<?php if(!empty($videoDesc)) : ?>
				<p class="video-desc">
					<?php echo $videoDesc ?>
				</p>
				<?php endif; ?>
				
				
				</div>
				
				<?php 
			}
		}
		?>
		
		<?php if (isset($prog->actors) && !empty($prog->directors)): ?>
		<p>В ролях:
			<ul class="persons btn-group">
				<?php foreach ($prog->actors as $p): ?>
				<li class="btn btn-mini">
					<?php echo $p['complete_name'] ?>
				</li>
				<?php endforeach; ?>
			</ul>
		</p>
		<?php endif; ?>
		
		<?php if (isset($prog->directors) && !empty($prog->directors)): ?>
		<p>Режиссер:
			<ul class="persons btn-group">
				<?php foreach ($prog->directors as $p): ?>
				<li class="btn btn-mini">
					<?php echo $p['complete_name'] ?>
				</li>
				<?php endforeach; ?>
			</ul>
		</p>
		<?php endif;  ?>
		
	</div>
	
	<?php 
	}
	?>
	</div>
	
	
	
	<div id="slides-nav">
		<?php /*<a data-slide="prev" href="#programslist" class="left carousel-control btn">‹</a>*/?>
		<a data-slide="next" href="#programslist" class="right btn">Далее</a>
	</div>
</div>




<?php
/*
 * Ссылка tinyurl
 */ 
?>
<p>
<em>Короткая ссылка на программу канала <?php echo $channelTitle ?></em> <a href="<?php echo $this->short_link ?>" 
	title="<?php printf('Телепрограмма канала %s на каждый день', $channelTitle) ?>"
	class="badge badge-important"
	rel="nofollow"><?php echo $this->short_link; ?></a>
</p>

<?php
/*
 * Сссылка на расписание не неделею
 */ 
?>
<?php if (!$this->is_today) : ?>
<p>
	<a href="<?php echo $this->url(array('channel'=>$this->channel->alias), 'default_listings_day-listing'); ?>"
		title="<?php printf('Перейти к расписанию программ канала %s на сегодня', $channelTitle); ?>">
		<em><?php printf ('Программа передач "%s" на сегодня', $channelTitle) ?></em>
	</a>
</p>
<?php endif; ?>
<p>
	<a href="<?php echo $this->url(array('channel'=>$this->channel->alias), 'default_channels_channel-week'); ?>"
		title="<?php printf('Перейти к расписанию программ канала %s на неделю', $channelTitle); ?>">
		<em><?php printf ('Программа передач "%s" на всю неделю', $channelTitle) ?></em>
	</a>
</p>


<?php
/*
 * Сылки Вчера, Завтра и Все каналы
 */ 
?>
<ul id="daynav" class="nav nav-pills">
	<li>
		<?php 
		//var_dump($this->listing_date->toString('dd-MM-yyyy'));
		//die(__FILE__.': '.__LINE__);
		$d = new Zend_Date($this->listing_date->toString('U'), 'U');
		$d->subDay(1);
		?>
		<a href="<?php echo $this->url(array('channel'=>$this->channel->alias, 'date'=>$d->toString('dd-MM-yyyy')), 'default_listings_day-date') ?>"
			class="btn"
			title="Программа <?php echo $this->channel->title ?> на <?php echo $d->toString('dd-MM-yyyy') ?>">Вчера</a>
	</li>
	<li>
		<a href="<?php echo $this->url(array(), 'default_channels_list') ?>" class="btn" title="Все телеканалы">Все каналы</a>
	</li>
	<li>
		<?php 
		$d = new Zend_Date($this->listing_date->toString('U'), 'U');
		$d->addDay(1);
		?>
		<a href="<?php echo $this->url(array( 'channel'=>$this->channel->alias, 'date'=>$d->toString('dd-MM-yyyy')), 'default_listings_day-date') ?>"
			class="btn"
			title="Программа <?php echo $this->channel->title ?> на <?php echo $d->toString('dd-MM-yyyy') ?>">Завтра</a>
	</li>
	
</ul>



<?php 
/*
 * Torrent links
 */
if ($this->torrent_links) { 
	//var_dump($this->torrent_links);
	?>
<ul class="dl">
	
	<?php 
	foreach ($this->torrent_links as $item){
		?>
		<li>
			<img src="/images/icons/arrow_down_24x24.png">
			<a rel="nofollow" href="<?php echo $item->url; ?>" target="_blank">
				<?php echo $this->truncateString($item->title, 18, 'words') ; ?>
			</a>
		</li>
		<?php
		$k++; 
	}
	?>
	
</ul>
<?php 
} ?>

<?php




} else {
	
	
	
	
?>
<p>К сожалению в выбранный вами период программ не найдено. Попробуйте посетить эту страницу позже.</p>
<div id="DIV_DA_78319"></div>
<?php 
}?>



<?php 
//die(__FILE__.': '.__LINE__);

if (!empty($this->comments)) { ?>
<div id="comments">
	<h4><?php printf('<strong>В блогах  про %s</strong>', $channelTitle) ?></h4>
	<?php
	foreach ($this->comments as $comment) {
		//var_dump($comment);
		//die(__FILE__.': '.__LINE__);
		?>
	<div xmlns:v="http://rdf.data-vocabulary.org/#" typeof="v:Review" class="hreview">
		
		<?php if (!empty($comment['title'])) : ?>
		<div class="summary"><?php echo $comment['title'] ?></div>
		<?php else: ?>
		<div class="summary">
			<span property="v:itemreviewed"><?php echo $this->escape( $this->channel->title ); ?></span>
		</div>
		<?php endif; ?>
		
		
		<?php if (!empty($comment['author'])) : ?>
		<div class="author">
			<a href="<?php echo $comment['src_url']  ?>" rel="nofollow" target="_blank">
				<small><span property="v:reviewer"><?php echo $comment['author'] ?></span></small>
			</a>
		</div>
		<?php endif; ?>
		
		
		<?php if (!empty($comment['date_created'])) { ?>
		<div class="date">
			<?php echo $comment['date_created']->toString('EEEE, dd MMM yyyy hh:mm'); ?>
			<span property="v:dtreviewed" content="<?php echo $comment['date_created']->toString('yyyy-MM-dd') ?>">
		</div>
		<?php 
		} ?>
		
		
		<div class="description">
			<span property="v:description">
				<?php echo str_ireplace($this->channel->title, '<em>'.$this->channel->title.'</em>', $comment['intro']) ?>
			</span>
		</div>
		
		<span property="v:rating"></span>
		
	</div>
		<?php 
	}
	?>
	<a href="<?php //echo $this->url(array(), 'default_comments_create'); ?>">Добавить комментарий</a>
</div>
<div class="copy3rdparty">
	<a href="http://blogs.yandex.ru/" title="Yandex поиск по блогам" rel="nofollow"><img src="http://img.yandex.net/i/logo100x43.png" width="37" height="16" /></a>
</div>
<?php 
} ?>