<?php 
/**
 * Day listing script for channel
 * 
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: day-listing.phtml,v 1.10 2012-12-25 01:57:53 developer Exp $
 *
 */
$this->headScript()
	->appendFile($this->baseUrl()."/js/listing-day.js")
	->appendScript("$('.carousel').carousel('pause');
	$.getJSON( '/channels/update-comments/format/html/channel/".$this->channel->ch_alias."', function(response) {
		
	});
	");

	
//var_dump($this->channel);
//die(__FILE__.': '.__LINE__);
	
$channelTitle = $this->escape($this->channel->title);

/*
 * Generate keywords
 */
$kw = array($channelTitle, $this->listing_date->toString('d MMMM YYYY'));
if (!empty($this->programs)) {
	foreach ($this->programs as $p) {
		if (count($kw)<5) {
			if (!in_array($p->title, $kw))
			$kw[]= Xmltv_String::strtolower( htmlspecialchars( $p->title, ENT_NOQUOTES, 'utf-8' ) );
		}
	}
}
$this->headMeta()->setName('keywords', implode(',', $kw) );


if ($this->is_today) {
	//META title
	$this->headMeta()->setName('title', sprintf ('Программа телеканала %s на сегодня, %s. Видео записей программ.', $channelTitle, $this->listing_date->toString( 'EEEE, d MMMM YYYY' )));
	//Browser window title
	$this->headTitle( sprintf ('Телепрограмма и видео с канала %s на сегодня', $channelTitle ) );
} else {
	//META title
	$this->headMeta()->setName('title', sprintf ('Программа канала %s за %s. Видео записей программ.', $channelTitle, $this->listing_date->toString('EEEE, d MMMM YYYY')));
	//Browser window title
	$this->headTitle( sprintf ('Телепрограмма %s за %s', $channelTitle, $this->listing_date->toString( 'EEEE, d MMMM YYYY' ) ) );
}

?>

<div class="forms2">
	<div id="fastsearch-wrap">
		<?php echo new Xmltv_Form_FastChannelSearchForm(array('label_class'=>'smallheading')); ?>
	</div>
	<?php echo new Xmltv_Form_TimezoneSwitch(array('label_class'=>'smallheading', 'time_shift'=>$this->timeshift)); ?>
</div>


<h1>
	<?php
	if ($this->is_today){
		printf('Программа «%s» сегодня', $channelTitle); 
	} else {
		printf('Программа «%s» %s', $channelTitle, $this->listing_date->toString('d MMMM YYYY'));
	}?>
</h1>

<?php if ($this->is_today) : ?>
<strong><?php echo Xmltv_String::ucfirst( $this->listing_date->toString("EEEE, d MMMM YYYY") ); ?></strong>
<?php endif; ?>




<?php 
if (!empty($this->programs)) {
?>
<a class="btn btn-mini btn-primary" id="slideshow_onoff" href="#">Показать расписание списком</a>
<br />


<?php /*<a href="<?php echo $this->url(array('w'=>$this->channel->title), 'default_torrents_finder') ?>">Торренты</a> */ ?>
<?php echo $this->partialLoop('patials/torrents-listing.phtml'); ?>

<?php 
/*
 * Programs list
 */
?>
<div id="programslist" class="carousel slide">
	<div class="carousel-inner" id="programs-carousel">
	<?php 
	foreach ($this->programs as $k=>$prog) {
		
		if ($this->is_today) {
			$active = $prog->now_showing===true ? ' active' : '' ;
		} else {
			$active = $k==0 ? ' active' : '' ;
		}
		?>
	<div class="item<?php echo $active; ?> programcontainer">
		
		<div class="program-times">
			<div class="time start">
				<span class="start_time"><?php echo $prog->start->toString('HH:mm') ?></span>
			</div>
			<div class="time end">
				<span class="end_time"><?php echo $prog->end->toString('HH:mm') ?></span>
			</div>
		</div>
		
		<div class="programtitle">
			<h3>
				<?php if ($this->is_today) : ?>
				<a href="<?php printf( '/телепрограмма/%s/%s/сегодня', $this->channel->ch_alias, $prog->alias  ); ?>">
					<?php echo ltrim( trim($prog->title, ':.'), '"'); ?>
				</a>
				<?php else : ?>
				<a href="<?php printf( '/телепрограмма/%s/%s/%s', $this->channel->ch_alias, $prog->alias, $this->listing_date->toString("yyyy-MM-dd")  ); ?>">
					<?php echo trim($prog->title, ':') ?>
				</a>
				<?php endif; ?>
			</h3>
			
			<?php if (!empty($prog->sub_title)) : ?>
			<h4 class="subtitle"><?php echo $prog->sub_title ?></h4>
			<?php endif; ?>
		</div>
		
		<?php if (isset($prog->rating) && $prog->rating>0) : ?>
		<p class="rating">Возрастной рейтинг: 
			<span class="label label-warning"><?php echo $prog->rating ?>+</span>
		</p>
		<?php endif; ?>
		
		<p>
			<a class="btn btn-mini btn-primary" title="Скачать <?php echo $prog->title ?>" href="<?php echo $this->url(array(), 'default_torrents_finder') ?>?s=<?php echo urlencode(strrev(base64_encode($prog->title))); ?>">
				Скачать <?php echo $prog->title ?>
			</a>
		</p>
		
		<?php if (!empty($prog->desc_intro)) : ?>
		<p class="desc intro"><?php echo $this->truncateString( $prog->desc_intro, 100, 'words' ) ?></p>
		<?php endif; ?>
		
		<?php if (!empty($prog->desc_body)) : ?>
		<p class="desc body"><?php echo $this->truncateString( $prog->desc_body, 100, 'words' ) ?></p>
		<?php endif; ?>
		
		
		<?php 
		/*
		 * Videos
		 */
		//var_dump(count($this->listing_videos));
		if (count($this->listing_videos)) {
			if (array_key_exists($prog->hash, $this->listing_videos)){
				$vid = $this->listing_videos[$prog->hash];
				//var_dump($this->listing_videos[$prog->hash]);
				?>
				
				<div class="program-video">
				<?php 
				
				$videoTitle = $this->escape( $vid->title );
				$videoAlias = $this->escape( $vid->alias );
				$videoDesc  = $this->escape( $vid->desc );
				$videoId	= $vid->rtvg_id;
				$videoUrl   = $this->url(array('alias'=>$videoAlias, 'id'=>$videoId), 'default_videos_show-video');
				?>
				
				
				<?php
				$wrapStyle = empty($videoDesc) ? 'width: 100%;' : 'float:left; width:120px; margin: 0 1em 0.25em 0;' ;
				?>
				<div style="<?php echo $wrapStyle ?>" itemscope itemtype="http://schema.org/ImageObject">
				<?php 
				$thumbs = $vid->thumbs; 
				foreach ($thumbs as $thumb){
					$thW = (int)Zend_Registry::get('site_config')->videos->listing->get('thumb_width', 240);
					?>
					<a href="<?php echo $videoUrl ?>"
						title="Видео, похожие на <?php echo $videoTitle ?>">
						<img src="<?php echo $thumb->url ?>" width="<?php echo $thW ?>" alt="<?php echo $videoTitle ?>" />
					</a>
					<?php 
				}
				?>
				</div>
				
				<h3 class="title">
					<?php $vlink = empty($videoDesc) ? $videoTitle.$this->truncateString( $videoDesc, 40, 'letters') : $videoTitle; ?>
					<?php echo $vlink ?>
					<a class="video-link" href="<?php echo $videoUrl; ?>" title="Нажмите чтобы смотреть <?php echo $videoTitle; ?> сейчас">
						Смотреть
					</a>
					
				</h3>
				
				<?php if(!empty($videoDesc)) : ?>
				<p class="video-desc">
					<?php echo $this->truncateString( $videoDesc, 40, 'words' ); ?>
				</p>
				<?php endif; ?>
				
				
				</div>
				
				<?php 
			}
		}
		?>
		
	</div>
	
	<?php 
	}
	?>
	</div>
	
	<?php
	/*
	 * Ссылка tinyurl
	 */ 
	?>
	<p>
	Короткая ссылка на эту страницу: <a href="<?php echo $this->short_link ?>" 
		title="<?php printf('Телепрограмма канала %s на каждый день', $channelTitle) ?>"
		class="badge badge-important"
		rel="nofollow"><?php echo $this->short_link; ?></a>
	</p>
	
	<?php
	/*
	 * Сссылка на расписание не неделею
	 */ 
	?>
	<?php if ($this->is_today) : ?>
	<p>
		<a href="<?php echo $this->url(array('channel'=>$this->channel->ch_alias), 'default_channels_channel-week'); ?>"
			title="<?php printf('Перейти к расписанию программ канала %s на неделю', $channelTitle); ?>">
			<em><?php printf ('Программа передач "%s" на всю неделю', $channelTitle) ?></em>
		</a>
	</p>
	<?php endif; ?>
	
	<?php
	/*
	 * Сылки Вчера, Завтра и Все каналы
	 */ 
	?>
	<ul id="daynav" class="nav nav-pills">
		<li>
			<?php 
			$d = new Zend_Date($this->listing_date->toString('U'), 'U');
			$d->subDay(1);
			?>
			<a href="<?php echo $this->url(array(
				'channel'=>$this->channel->ch_alias,
				'date'=>$d->toString('dd-MM-yyyy')), 'default_listings_day-date') ?>"
				class="btn"
				title="Программа <?php echo $this->channel->title ?> на <?php echo $d->toString('dd-MM-yyyy') ?>">Вчера</a>
		</li>
		<li>
			<a href="<?php echo $this->url(array(), 'default_channels_list') ?>" 
				class="btn"
				title="Все телеканалы">Все каналы</a>
		</li>
		<li>
			<?php 
			$d = new Zend_Date($this->listing_date->toString('U'), 'U');
			$d->addDay(1);
			?>
			<a href="<?php echo $this->url(array(
				'channel'=>$this->channel->ch_alias,
				'date'=>$d->toString('dd-MM-yyyy')), 'default_listings_day-date') ?>"
				class="btn"
				title="Программа <?php echo $this->channel->title ?> на <?php echo $d->toString('dd-MM-yyyy') ?>">Завтра</a>
		</li>
		
	</ul>
	
	<?php 
	/*
	 * Torrent links
	 */
	if ($this->torrent_links) { 
		//var_dump($this->torrent_links);
		?>
	<ul class="dl">
		
		<?php 
		foreach ($this->torrent_links as $item){
			?>
			<li>
				<img src="/images/icons/arrow_down_24x24.png">
				<a rel="nofollow" href="<?php echo $item->url; ?>" target="_blank">
					<?php echo $this->truncateString($item->title, 6, 'words') ; ?>
				</a>
			</li>
			<?php
			$k++; 
		}
		?>
		
	</ul>
	<?php 
	} ?>
	
	<div id="slides-nav">
		<a data-slide="prev" href="#programslist" class="left carousel-control btn">‹</a>
		<a data-slide="next" href="#programslist" class="right carousel-control btn">›</a>
	</div>
</div>
<?php




} else {
	
	
	
	
?>
<p>К сожалению в выбранный вами период программ не найдено. Попробуйте посетить эту страницу позже.</p>
<div id="DIV_DA_78319"></div>
<?php 
}?>



<?php 
//die(__FILE__.': '.__LINE__);

if (!empty($this->comments)) { ?>
<div id="comments">
	<h3><?php printf('<strong>В блогах  про %s</strong>', $channelTitle) ?></h3>
	<br />
	<?php
	foreach ($this->comments as $comment) {
		//var_dump($comment);
		?>
	<div class="comment">
	
		<div class="title"><?php echo @$comment['title'] ?></div>
		
		<div class="author">
			<a href="<?php echo $comment['src_url']  ?>" rel="nofollow" target="_blank">
				<small><?php echo $comment['author'] ?></small>
			</a>
		</div>
		
		<div class="date">
		<?php  
		if (!is_a($comment['date_created'], 'Zend_Date'))
		$date = new Zend_Date($comment['date_created']);
		else
		$date = $comment['date_created'];
		
		echo $date->toString('EEEE, dd MMM yyyy hh:mm');
		?>
		</div>
		
		<div class="intro">
			<?php echo str_ireplace($channelTitle, '<em>'.$channelTitle.'</em>', $comment['intro']) ?>
		</div>
		
		<?php if (!empty($comment['fulltext'])): ?>
		<div class="fulltext"></div>
		<?php endif; ?>
		
	</div>
		<?php 
	}
	?>
	<a href="<?php echo $this->url(array(), 'default_comments_create'); ?>">Добавить комментарий</a>
</div>
<div class="copy3rdparty">
	<a href="http://blogs.yandex.ru/" title="Yandex поиск по блогам" rel="nofollow"><img src="http://img.yandex.net/i/logo100x43.png" width="37" height="16" /></a>
</div>
<?php 
} ?>