<?php 
/**
 * Day listing script for channel
 * 
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: day-listing.phtml,v 1.9 2012-08-13 13:20:15 developer Exp $
 *
 */
$this->headScript()
	//->appendFile($this->baseUrl()."/js/bootstrap-carousel.js")
	->appendFile($this->baseUrl()."/js/listing-day.js")
	->appendScript("$('.carousel').carousel('pause')");

/*
 * figure out if current day is today
 */
$this->is_today=false;
$date = new Zend_Date(null, null, 'ru');
if ($this->today->toString('yyyy-MM-dd')==$date->toString('yyyy-MM-dd')) 
$this->is_today=true;

$tolower = new Zend_Filter_StringToLower();
$channelTitle = $this->escape( $this->channel->title );
$channelAlias = Xmltv_String::strtolower( $this->escape( $this->channel->alias ));

/*
 * Set META title
 */
if ($this->is_today)
	$this->headMeta()->setName('title', sprintf ('Программа телеканала %s на сегодня', $channelTitle));
else
	$this->headMeta()->setName('title', sprintf ('Программа канала %s за %s', $channelTitle, $this->today->toString('EEEE, d MMMM YYYY')));

/*
 * Set browser window title
 */
if ($this->is_today)
	$this->headTitle( sprintf ('Телепрограмма канала %s на сегодня, %s', $channelTitle, $this->today->toString( 'EEEE, d MMMM YYYY' ) ) );
else
	$this->headTitle( sprintf ('Телепрограмма %s за %s', $channelTitle, $this->today->toString( 'EEEE, d MMMM YYYY' ) ) );


/*
 * prevent indexing of time-shifted pages
 */
if ((int)$this->timeshift!=0) {
	$this->headMeta()->setName('robots', 'noindex,follow');
}

/*
 * Generate keywords
 */
$kw = array($tolower->filter( $channelTitle ), $this->today->toString('d MMMM YYYY'));
if (!empty($this->programs)) {
	foreach ($this->programs as $p) {
		if (count($kw)<5) {
			if (!in_array($p->title, $kw))
			$kw[]= Xmltv_String::strtolower( htmlspecialchars( $p->title, ENT_NOQUOTES, 'utf-8' ) );
		}
	}
}
$this->headMeta()->setName('keywords', implode(',', $kw) );


?>

<div class="forms2">
	<div id="fastsearch-wrap">
		<?php 
		$form = new Xmltv_Form_FastChannelSearchForm(array('label_class'=>'smallheading'));
		echo $form;
		?>
	</div>
	<?php 
	$form = new Xmltv_Form_TimezoneSwitch(array('label_class'=>'smallheading', 'time_shift'=>$this->timeshift));
	echo $form; 
	?>
</div>


<h1><?php printf('Канал %s сегодня', $channelTitle) ?></h1>

<p><?php echo Xmltv_String::ucfirst( $this->today->toString("EEEE, d MMMM YYYY") ); ?></p>
<p>
	<a class="btn week btn-mini" title="<?php printf('Перейти к расписанию программ канала %s на неделю', $channelTitle); ?>" href="/телепрограмма/<?php echo Xmltv_String::strtolower( $channelAlias ) ?>/неделя">
		<?php printf ('Программа передач "%s" на всю неделю', $channelTitle) ?>
	</a>
</p>

<?php 
if (!empty($this->programs)) {
?>
<a class="btn btn-mini btn-primary" id="slideshow_onoff" href="#">Показать расписание списком</a>
<div id="programslist" class="carousel slide">
	<div class="carousel-inner" id="programs-carousel">
	<?php 
	
	///var_dump($this->programs);
	//die(__FILE__.": ".__LINE__);
	
	foreach ($this->programs as $k=>$prog) {
		
		//var_dump($prog);
		//die(__FILE__.': '.__LINE__);
		
		if ($this->is_today)
		$active = $prog->now_showing===true ? ' active' : '' ;
		else
		$active = $k==0 ? ' active' : '' ;
		
		$prog->title = preg_replace('/([\w]+)\.[\w]+/ui', '\1. ', $prog->title);
		
		?>
	<div class="item<?php echo $active; ?> programcontainer">
		
		<div class="program-times">
			<div class="time start">
				<span class="start_time"><?php echo $prog->start->toString('HH:mm') ?></span>
			</div>
			<div class="time end">
				<span class="end_time"><?php echo $prog->end->toString('HH:mm') ?></span>
			</div>
		</div>
		
		<div class="programtitle">
			<h3>
				<?php $prog_title = $prog->title; ?> 
				<?php if ($this->is_today) : ?>
				<a href="<?php printf( '/телепрограмма/%s/%s/сегодня', $channelAlias, $prog->alias  ); ?>"><?php echo ltrim( trim($prog_title, ':.'), '"'); ?></a>
				<?php else : ?>
				<a href="<?php printf( '/телепрограмма/%s/%s/%s', $channelAlias, $prog->alias, $this->today->toString("yyyy-MM-dd")  ); ?>"><?php echo trim($prog->title, ':') ?></a>
				<?php endif; ?>
			</h3>
			
			<?php if (!empty($prog->sub_title)) : ?>
			<p class="subtitle"><?php echo $prog->sub_title ?></p>
			<?php endif; ?>
		</div>
		
		<?php if (!empty($prog->desc_intro)) : ?>
		<p class="desc intro"><?php echo $this->truncateString( $prog->desc_intro, 100, 'words' ) ?></p>
		<?php endif; ?>
		
		<?php if (!empty($prog->desc_body)) : ?>
		<p class="desc body"><?php echo $this->truncateString( $prog->desc_body, 100, 'words' ) ?></p>
		<?php endif; ?>
		
		
				
				
				
		<?php 
			
		$query = array();
		$query = explode(' ', preg_replace('/[^\w\d]/ui', ' ', $prog->title));
		//var_dump($query);
		$kwAmount = 3;
		foreach ($query as $k=>$v) {
			$word = trim($v);
			if(!empty($word) && Xmltv_String::strlen($v)>3 )
				$query[$k] = Xmltv_String::strtolower($v);
			else
				unset($query[$k]);
		}
		sort($query);
		//var_dump($query);
	
		if ( count($query) > $kwAmount ){
			$k = (count($query)-1);
			do {
				unset($query[$k]);
				$k--;
			} while (count($query)>$kwAmount);
		}
		
		//var_dump($query);
		//die(__FILE__.': '.__LINE__);
		if (count($query)) {
		$youtube = new Xmltv_Youtube(array(
			'max_results'=>3,
			'order'=>'relevance',
			'unique_token'=>'program-listing'
		));
		$videos = $youtube->fetchVideos($query);
		
		//var_dump(count($videos));
		//die(__FILE__.': '.__LINE__);
		if (count($videos)) {
			?>
			<div class="program-video">
			<?php 
			if ($current = $videos->offsetGet(1))  {
				
				$videoTitle = $current->getVideoTitle();
				$videoAlias = $this->videoAlias( $videoTitle );
				$videoDesc  = $current->getVideoDescription();
				$videoId    = $this->videoId( $current->getVideoId() );
				?>
				
				<h3>
					<?php 
					$link_title = empty($videoDesc) ? $videoTitle. $this->truncateString( $videoDesc, 40, 'letters') : $videoTitle ; 
					$link_href = "/видео/онлайн/".$videoAlias .'/'. $videoId;
					?>
					<a class="video-link" href="<?php echo $link_href; ?>" title="<?php echo $link_title; ?>">
						<?php echo $videoTitle ?> Видео
					</a>
				</h3>
					
				<?php 
				try {
					$videoThumbnails = $current->getVideoThumbnails();
				} catch (Exception $e) {
					echo $e->getMessage();
				}
				$k=0;
				foreach($videoThumbnails as $videoThumbnail) {
					if ($videoThumbnail['width'] >= 200) {
						
						?>
						<a href="/видео/онлайн/<?php echo $videoAlias .'/'. $videoId ?>">
							<img src="<?php echo $videoThumbnail['url'] ?>" width="240" alt="<?php echo $videoTitle ?>" />
						</a>
						
						<?php 
						break;
					}
					$k++;
				}
				?>
				
				<?php if(!empty($videoDesc)) : ?>
				<p class="video-desc">
					<?php
					$desc_short = $this->truncateString( $videoDesc, 40, 'words' );
					//echo $this->synonimize($desc_short);
					echo $desc_short; ?>
				</p>
				<?php endif; ?>
				
				<?php 
					
				
			} 
			?>
			</div>	
			<?php 
		}
		}
		?>
		
	</div>
	<?php 
	}
	//die(__FILE__.': '.__LINE__);
	?>
	</div>
	<div id="slides-nav">
		<a data-slide="prev" href="#programslist" class="left carousel-control btn">‹</a>
		<a data-slide="next" href="#programslist" class="right carousel-control btn">›</a>
	</div>
</div>
<?php

} else {
?>
<p>К сожалению в выбранный вами период программ не найдено. Попробуйте посетить эту страницу позже.</p>
<div id="DIV_DA_78319"></div>
<?php 
}?>

<div class="pager" id="neighbor_days">
	<div class="previous">
		<?php 
		$y = $this->today;
		$y->subDay(1, $y, 'ru'); 
		?>
		<a href="<?php printf ('/телепрограмма/%s/%s', $channelAlias, $y->toString('yyyy-MM-dd')) ?>" title="" class="btn prev">Программы вчера</a>
	</div>
	<div class="next">
		<?php 
		$t = $this->today;
		$t->addDay(2, $t, 'ru');
		?>
		<a href="<?php printf ('/телепрограмма/%s/%s', $channelAlias, $t->toString('yyyy-MM-dd')) ?>" style="float:right;" class="btn next" title="">Программы завтра</a>
	</div>
	
</div>

<div class="pager" style="text-align:center;">
	<a class="btn btn-info" id="allchannnels" href="/телепрограмма" title="Все телеканалы">Все каналы</a>
</div>

<?php 
//die(__FILE__.': '.__LINE__);

if (!empty($this->comments)) { ?>
<div id="comments">
	<h3><?php printf('Комментарии пользователей про телеканал "%s"', $channelTitle) ?></h3>
	<br />
	<a href="/комменты/новый">Добавить комментарий</a>
	<?php
	foreach ($this->comments as $comment) {
		//var_dump($comment);
		?>
	<div class="comment">
	
		<div class="title"><?php echo @$comment['title'] ?></div>
		
		<div class="author">
			<a href="<?php echo $comment['src_url']  ?>" rel="nofollow" target="_blank">
				<small><?php echo $comment['author'] ?></small>
			</a>
		</div>
		
		<div class="date">
		<?php  
		if (!is_a($comment['date_created'], 'Zend_Date'))
		$date = new Zend_Date($comment['date_created']);
		else
		$date = $comment['date_created'];
		
		echo $date->toString('EEEE, dd MMM yyyy hh:mm');
		?>
		</div>
		
		<div class="intro"><?php echo $comment['intro'] ?></div>
		
		<?php if (!empty($comment['fulltext'])): ?>
		<div class="fulltext"></div>
		<?php endif; ?>
		
	</div>
		<?php 
	}
	?>
</div>
<div class="copy3rdparty">
	<a href="http://blogs.yandex.ru/" title="Yandex поиск по блогам" rel="nofollow"><img src="http://img.yandex.net/i/logo100x43.png" width="37" height="16" /></a>
</div>
<?php 
} ?>