<?php 
/**
 * Расписание на день
 * 
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: day.phtml,v 1.2 2012-04-01 04:57:55 dev Exp $
 *
 */
$this->headScript()
	->appendFile($this->baseUrl()."/js/bootstrap-carousel.js")
	->appendFile($this->baseUrl()."/js/listing-day.js");

$channel_alias = Xmltv_String::strtolower($this->channel['alias']);

$this_day_is_today=false;
$date = new Zend_Date(null, null, 'ru');
if ($this->today->toString('yyyy-MM-dd')==$date->toString('yyyy-MM-dd')) 
$this_day_is_today=true;

$css = ".carousel-inner { }";
$this->headStyle()->appendStyle($css);

?>
<div id="fast_search">
	<?php
	$form = new Xmltv_Form_FastChannelSearchForm();
	echo $form;
	/*
	<label for="channel_filter">Быстрый переход</label>
	<input type="text" name="fast_search" data-provide="typeahead" />
	*/ ?>
</div>
<h1><?php printf('Канал %s сегодня', $this->channel['title']) ?></h1>
<p><?php echo Xmltv_String::ucfirst( $this->today->toString("EEEE, d MMMM YYYY") ); ?></p>
<p><?php echo $this->channel->desc['intro'] ?></p>
<p><?php echo $this->channel->desc['body'] ?></p>
<p><a class="btn" href="<?php printf ('/телепрограмма/%s/неделя', $channel_alias) ?>" title=""><?php printf ('Программа канала %s на всю неделю', $this->channel['title']) ?></a></p>

<?php 
if (!empty($this->programs)) {
?>
<a id="slideshow_onoff" href="#">Показать расписание списком</a>
<div id="programslist" class="carousel">
	<div class="carousel-inner" id="programs-carousel">
	<?php 
	foreach ($this->programs as $k=>$prog) {
		//var_dump($prog);
		if ($this_day_is_today)
		$active = $prog['now_showing']===true ? ' active' : '' ;
		else
		$active = $k==0 ? ' active' : '' ;
		?>
	<div class="item<?php echo $active; ?> programcontainer">
		<div class="programtitle">
		
			<p class="start"><span class="start_time"><?php echo $prog['start']->toString(Zend_Date::HOUR.':'.Zend_Date::MINUTE) ?></span></p>
		
			<h3>
				<?php 
				$prog_title = $prog['title'];
				$maxLen = 40;
				if (Xmltv_String::strlen($prog['title'])>$maxLen) {
					$parts = explode(' ', $prog['title']);
					$prog_title = '';
					foreach ($parts as $word){
						if ((Xmltv_String::strlen(trim($prog_title))+Xmltv_String::strlen(trim($word))) <= $maxLen)
						$prog_title.=' '.$word;
					}
					$prog_title.='&hellip;';
				}
				?>
				<?php if ($this_day_is_today) : ?>
				<a href="<?php printf( '/телепрограмма/%s/%s/сегодня', $channel_alias, $prog['alias']  ); ?>"><?php echo $prog_title ?></a>
				<?php else : ?>
				<a href="<?php printf( '/телепрограмма/%s/%s/%s', $channel_alias, $prog['alias'], $this->today->toString("yyyy-MM-dd")  ); ?>"><?php echo $prog['title'] ?></a>
				<?php endif; ?>
			</h3>
			
			<?php if (!empty($prog['sub_title'])) : ?>
			<p><?php echo $prog['sub_title'] ?></p>
			<?php endif; ?>
			
			<p class="end"><span class="end_time"><?php echo $prog['end']->toString(Zend_Date::HOUR.':'.Zend_Date::MINUTE) ?></span></p>
			
			<?php if (!empty($prog['desc']['intro'])) : ?>
			<p class="desc"><?php echo $prog['desc']['intro'] ?></p>
			<?php endif; ?>
			
		</div>
		<p class="desc intro"></p>
		<p class="desc body"></p>
	</div>
	<?php 
} ?>
	</div>
	<div id="slides-nav">
		<a data-slide="prev" href="#programslist" class="left carousel-control btn btn-warning">‹</a>
		<a data-slide="next" href="#programslist" class="right carousel-control btn btn-warning">›</a>
	</div>
</div>
<?php
} else {
?>
<p>К сожалению в выбранный вами период программ не найдено. Попробуйте посетить эту страницу позже.</p>
<?php 
}?>


<div class="pager" id="neighbor_days">
	<div class="previous">
		<?php 
		$y = $this->today;
		$y->subDay(1, $y, 'ru'); 
		?>
		<a href="<?php printf ('/телепрограмма/%s/%s', $channel_alias, $y->toString('yyyy-MM-dd')) ?>" title="" class="prev">Программы вчера</a>
	</div>
	<div class="next">
		<?php 
		$t = $this->today;
		$t->addDay(2, $t, 'ru');
		?>
		<a href="<?php printf ('/телепрограмма/%s/%s', $channel_alias, $t->toString('yyyy-MM-dd')) ?>" style="float:right;" class="next" title="">Программы завтра</a>
	</div>
	
</div>

<div class="pager" style="text-align:center;">
	<a class="btn btn-info" id="allchannnels" href="/телепрограмма" title="Все телеканалы">Все каналы</a>
</div>