<?php 
$this->headScript()
	->prependFile($this->baseUrl()."/js/bootstrap-carousel.js")
	->prependFile($this->baseUrl()."/js/bootstrap.min.js");
$this->headScript()->appendScript("
	$('#programslist')..carousel('cycle').carousel('pause');
");
?>

<h1><?php printf('Канал %s сегодня', $this->channel['title']) ?></h1>

<?php
if ($this->is_today)
printf('Программы канала %s сегодня', $this->channel['title']);
else
printf('Канал %s %s', $this->channel['title'], $this->date->toString("EEEE, dd mm YYYY"));
?>

<p><?php echo $this->channel->desc['intro'] ?></p>
<p><?php echo $this->channel->desc['body'] ?></p>

<div id="programslist" class="carousel">
	<div class="carousel-inner">
<?php 
foreach ($this->programs as $prog) {
	//var_dump($prog['alias']);
	//die();
	?>
	<div class="item<?php echo $prog['now_showing']===true ? ' active' : '' ; ?> programcontainer">
		<div class="programtitle">
			<p>Начало: <span class="start_time"><?php echo $prog['start']->toString(Zend_Date::HOUR.':'.Zend_Date::MINUTE) ?></span></p>
			<h3><?php echo $prog['title'] ?></h3>
			<?php if (!empty($prog['sub_title'])) : ?>
			<p><?php echo $prog['sub_title']; ?></p>
			<?php endif; ?>
			<p>Заканчивается: <span class="end_time"><?php echo $prog['end']->toString(Zend_Date::HOUR.':'.Zend_Date::MINUTE) ?></span></p>
		</div>
		<p class="desc intro"></p>
		<p class="desc body"></p>
	</div>
	<?php 
} ?>
	</div>
	<a data-slide="prev" href="#programslist" class="left carousel-control">‹</a>
	<a data-slide="next" href="#programslist" class="right carousel-control">›</a>
</div>