<?php 
/**
 * Данные за время больше лимита
 *
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: outdated.phtml,v 1.2 2013-01-19 10:11:14 developer Exp $
 *
 */
$this->headMeta()->setName('robots', 'noindex,follow');
//Browser window title
$this->headTitle( 'Устаревшая программа' );
?>
<h1>Устаревшая программа</h1>
<p>К сожалению мы не сохраняем списки программ старее чем <?php echo $this->history_length ?> дней</p>