<?php 
/**
 * Выборанная программа сегодня
 * 
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: program-day.phtml,v 1.12 2013-03-14 06:09:55 developer Exp $
 *
 */
?>

<?
if (APPLICATION_ENV=='development') {
	//var_dump( $this->programs);
	//die(__FILE__.': '.__LINE__);
}

/*
 * Channel properties
 */
$channelTitle = $this->escape( $this->channel['title'] );
$channelAlias = $this->escape( $this->channel['alias'] );

/*
 * Generate keywords
 */
$kw = array(
	$channelTitle,
	$this->date->toString('d MMMM YYYY'),
	'сегодня'
);
if (count($this->programs)) {
	foreach ($this->programs as $p) {
		if (count($kw)<5) {
		    $t = Xmltv_String::strtolower( htmlspecialchars( $p['title'], ENT_NOQUOTES, 'utf-8' ) );
			if (!in_array($t, $kw)) {
				$kw[] = $t;
			}
		}
	}
}
$this->headMeta()->setName('keywords', implode(',', $kw) );

if (APPLICATION_ENV=='development') {
	//var_dump($this->current_program['title']);
	//die(__FILE__.': '.__LINE__);
}

if (!empty($this->programs)) {

	$programTitle = $this->escape( $this->current_program['title'] );
	$programAlias = $this->escape( $this->current_program['alias'] );
		
	if ($this->is_today) {
		//META title
		$this->headMeta()->setName('title', sprintf ('«%s» сегодня', $programTitle, $channelTitle));
		//page title
		$this->headTitle( sprintf ('Программа «%s» сегодня, %s, на канале «%s»', $programTitle, $this->escape( $this->date->toString('dd MMM')), $channelTitle));
	} else {
		//META title
		$this->headMeta()->setName('title', sprintf ('«%s» %s', $programTitle, $this->escape( $this->date->toString('dd MMM YYYY'))));
		//page title
		$this->headTitle( sprintf ('«%s» на канале «%s» %s', $programTitle, $channelTitle, $this->escape( $this->date->toString('dd MMM YYYY'))));
	}
	/*
	$start_times = array();
	foreach ($this->programs as $single) {
		$start = new Zend_Date( $single->start );
		$start_times[] = $this->escape( $start->toString( "HH:mm" ));
	}
	*/
	?>
	
	<div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="button" data-yashareQuickServices="vkontakte,facebook,twitter,odnoklassniki,moimir,moikrug,gplus,surfingbird"></div>
	
	<h1><?php echo $programTitle ?> на <?php echo $channelTitle ?></h1>
	
	<?php if (!$this->channel['desc_intro']): ?>
	<p><?php echo $this->truncateString( $this->escape( $this->channel['desc_intro'] ), 60, 'words', '.') ; ?></p> 
	<?php endif; ?>
	
	<p><a href="<?php echo $this->url( array('channel'=>$channelAlias), 'default_listings_day-listing'); ?>">
			<em>Программа <?php echo $channelTitle ?> на сегодня</em></a></p>
	<p><a href="<?php echo $this->url( array('channel'=>$channelAlias), 'default_channels_channel-week'); ?>">
			<em>Программа <?php echo $channelTitle ?> на неделю</em></a></p>
	
	<p class="label label-important">
		<a href="/телепрограмма/<?php echo $channelAlias.'/'.$programAlias?>/неделя" title="<?php echo $this->escape( sprintf("Все выпуски программы «%s» на этой неделе", $programTitle)) ?>">
			Искать <?php echo '"' . $programTitle . '"'?> на этой неделе
		</a>
	</p>
	
	<p><?php echo $this->truncateString( $this->channel['desc_intro'].$this->channel['desc_body'], 56, 'words' ) ; ?></p>
	<?php echo $this->partial( 'listings/partials/day-item.phtml', array( 'items'=>$this->programs )); ?>
	<?php
	
} else {
	
	/*
	 * Set META title
	 */
	if ($this->is_today) {
		$this->headMeta()->setName('title', "Эта программа сегодня не выходит");
	} else {
		$this->headMeta()->setName('title', sprintf ('Эта программа не выходит в эфир %s', $this->escape( $this->date->toString('dd MMM YYYY'))));
	}
	$this->headMeta()->setName('robots', 'noidex,follow');
	/*
	 * Set page title
	 */
	if ($this->is_today) {
		$this->headTitle( "Эта программа сегодня не выходит в эфир");
	} else {
		$this->headTitle( sprintf ('Эта программа не выходит в эфир %s', $this->escape( $this->date->toString('dd MMM YYYY'))));
	}
	?>
	<h2>Канал <?php echo $channelTitle ?></h2>
	<?php if (!empty($this->channel->desc_intro)): ?>
	<p><?php echo strip_tags( $this->channel->desc_intro ) ?></p> 
	<?php endif; ?>
	
	<p>Эта программа сегодня не выходит в эфир на канале <?php echo $channelTitle ?>.<br />
	<a class="btn btn-mini" href="/телепрограмма/<?php echo $channelAlias ?>">Программа <?php echo $channelTitle ?> на сегодня, <?php echo $this->escape( $this->date->toString('dd MMM YYYY')) ?></a>
	
<?php 

} ?>
<?php //die(__FILE__.': '.__LINE__); ?>




