<?php
/**
 * Программа на неделе
 * 
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: program-week.phtml,v 1.9 2012-12-25 02:14:18 developer Exp $
 *
 */

//var_dump($this->program);
//die(__FILE__.': '.__LINE__);

$programTitle = $this->escape( $this->program->title );
$programAlias = $this->escape( $this->program->alias );
$channelTitle = @isset($this->channel->title) ? $this->escape( $this->channel->title ) : '' ;
$channelAlias = @isset($this->channel->alias) ? $this->escape( Xmltv_String::strtolower( $this->channel->alias )): '' ;
?>

<div id="fast_search">
	<?php
	$form = new Xmltv_Form_FastChannelSearchForm();
	echo $form;
	?>
</div>



<h1>
	<i><?php echo $programTitle ?></i> на канале <i><?php echo $channelTitle ?></i>
</h1>

<p>
	<?php echo Xmltv_String::ucfirst( $this->week_start->toString('EEEE, d MMMM') ) ?> - <?php echo Xmltv_String::ucfirst( $this->week_end->toString('EEEE, d MMMM') ); ?>
</p>

<h2>
	<?php /*
	<a href="<?php echo $this->url( array('channel'=>$channelAlias), 'default_listings_day-date' ) ?>" 
		title="Телепрограмма <?php echo $channelTitle ?> на <?php echo $this->escape($this->program->start->toString('d MMM YYYY')) ?>">
		Программа передач <?php echo $channelTitle; ?> сегодня
	</a>
	*/ ?>
</h2>


<?php  
/**
 * If not found
 */
if (@isset($this->notfound) && $this->notfound===true) {
?>
<p>
	На этой неделе программу <em><?php echo $programTitle ?></em> показывать позже не будут. Но мы нашли похожие программы, которые возможно вас заинтересуют.
</p>

<table class="table table-condensed">
	<thead>
		<tr>
			<th>Время начала</th>
			<th>Программа</th>
			<th>Канал</th>
		</tr>
	</thead>
	<tbody>
		<?php
		foreach ($this->list as $single) {
			$program_start = new Zend_Date($single->start, 'YYYY-MM-dd HH:mm:ss' );
			$program_title = $single->title;
			$program_alias = $single->alias;
			$channel_title = $single->channel_title;
			$channel_alias = $single->channel_alias;
			?>
		<tr>
			<td><?php echo Xmltv_String::ucfirst( $program_start->toString( 'dd MMM в HH:mm', null, 'ru' ) ); ?></td>
			<td><?php echo $single->title ?></td>
			<td>
				<a href="/телепрограмма/<?php echo $channel_alias.'/'.$program_alias.'/'.$program_start->toString("YYYY-MM-dd").'/?layout=list#'.$program_start->toString("U"); ?>" target="_blank" title="Программа <?php echo $program_title ?> на канале <?php echo $channel_title.' '.$program_start->toString('EEEE, d YYYY') ?>">
					<?php echo $channel_title ?>
				</a>
			</td>
		</tr>
		
		<?php 
}
?>
	</tbody>
</table>

<?php
} else {
	/**
	 * If found
	 */
	$startDates = array();
	foreach ($this->list as $single) {
		//var_dump($single);
		//die();
		$singleAlias = $this->escape( $single->alias );
		//$start = $single->start->toString( 'YYYY-MM-dd HH:mm' );
		//$startDates[]= '<li><a href="/телепрограмма/'.$channelAlias.'/'.$singleAlias.'/'.$this->escape( $single->start->toString('yyyy-MM-dd') ).'">'.$this->escape( Xmltv_String::ucfirst( $single->start->toString( 'EEEE, d MMMM в HH:mm'))).'</a></li>';
	}
	?>

<p>
	На этой неделе вы можете посмотреть программу <b><?php echo $programTitle ?></b> на канале <a href="<?php echo '/телепрограмма/'.$channelAlias ?>" title="<?php echo $programTitle ?>"><i>«<?php echo $channelTitle ?>»</i></a> в следующие дни:
	<br/>
	<ul class="nav nav-tabs nav-stacked">
		<?php echo implode(PHP_EOL, $startDates); ?>
	</ul>
</p>

<?php 
} ?>

 

