<?php
/**
 * Похожие передачи на неделе при отсутствии основной на неделе позже
 *
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: similar-week.phtml,v 1.1 2013-01-19 10:11:14 developer Exp $
 *
 */
?>

<?php 
$this->headMeta()->setName( 'title', "Подобные передачи" );
$this->headTitle( $this->escape( 'Похожие программы на этой неделе :: rutvgid.ru'));

?>

<h1>Похожие программы на этой неделе</h1>

<?php 
if (isset($this->similar)) {
    foreach ($this->similar as $single) {
        $channelIcon = $this->baseUrl('images/channel_logo/'.$single->channel_icon);
        $date = new Zend_Date($single->start, 'YYYY-MM-dd HH:mm:ss' );
        $channelUrl = $this->url( array( 'channel'=>$single['channel_alias'] ), 'default_listings_day-listing' );
        $programUrl = $this->url( array('channel'=>$single['channel_alias'], 'date'=>$single['start']->toString("dd-MM-yyyy")), 'default_listings_day-date' ).'?ts='.$single['start']->toString("U");
		?>
		
		<p>
			<img src="<?php echo $channelIcon ?>" 
				alt="<?php echo $single->channel_title ?>" />
			
			<span class="label">
				<?php echo $single['start']->toString( 'dd MMMM') ?></span>&nbsp;<span class="label label-info"><?php echo $single['start']->toString( 'HH:mm') ?>
			</span>
			
			<?php printf('<a href="%s">%s</a> на канале <a href="%s" title="Передачи %s сегодня">%s</a>', 
				$programUrl, 
				$single['title'], 
				$channelUrl, 
				$single['channel_title'], 
				$single['channel_title'] );
			?>
			 
		</p>
		<?php 
    }
}
?>