<?php
$this->headTitle( sprintf("Онлайн-видео: %s", str_replace("\n", ' ', $this->main_video->getVideoTitle())));
$this->headMeta()->setName( 'description', $this->truncateString( str_replace( "\n", ' ', $this->main_video->getVideoDescription()), 12, 'words'));
$this->headMeta()->setName( 'keywords', Xmltv_String::strtolower( implode(',', $this->main_video->getVideoTags()) ));
$this->headScript()->appendFile("/js/swfobject/swfobject.js");
$this->headScript()->appendScript("$(document).ready(function() {
	var descP = $('.video.thumbnails .span4 p.desc');
	var descHeight = descP.prop('offsetHeight');
	if (descHeight>150) { descP.css({ height:'8.4em' }).after('<button class=\"btn\" id=\"fulldesc\">Читать полностью</a>'); }
	$('#fulldesc').click( function(e){ descP.css({ height:descHeight }); $(this).hide(500); });
	
});");

/*
 * banners
 */
/*
$ads = array(
	array(
		"title"=>'GTA 5 Online',
		"id"=>'82',
		"image"=>'images/ad/gta5.jpg',
		"url"=>'http://gta5.qr1x.asia/?r=12582',
	),
	array(
		"title"=>'Универ Онлайн',
		"id"=>'70',
		"image"=>'images/ad/univer.jpg',
		"url"=>'http://uuniveronline.qr1x.asia/?r=12582',
	),
	array(
		"title"=>'ВК Приложения',
		"id"=>'56',
		"image"=>'images/ad/vk-apps.jpg',
		"url"=>'http://vvkapps.e5xj.org/?r=12582',
	),
	array(
		"title"=>'Шаг вперёд 4',
		"id"=>'71',
		"image"=>'images/ad/stepforward4.jpg',
		"url"=>'http://sstepforward1.qr1x.asia/?r=12582',
	),
	array(
		"title"=>'Ваша диетка',
		"id"=>'23',
		"image"=>'images/ad/vasha-dieta.jpg',
		"url"=>'http://vassha-dieta.bg9.in/?r=12582',
	),
);
$idx = rand(0, count($ads)-1);
$banner = $ads[$idx];
*/
?>

<div class="page videos">
	<?php /*
	<div style="width:100%;">
		<div style="width:400px; height:175px; margin: 1.5em auto;">
			<a href="<?php echo $banner['url'] ?>" target="_blank">
				<img src="http://rutvgid.ru/<?php echo $banner['image'] ?>" alt="<?php echo $banner['title'] ?>" />
			</a>
		</div>
		<p class="desc"><?php echo strip_tags( $this->main_video->getVideoDescription() ) ?></p>
	</div>
	*/ ?>

	<div class="video main">
	
			<h1><?php echo $this->main_video->getVideoTitle() ?></h1>
			<p class="desc"><?php echo strip_tags( $this->main_video->getVideoDescription() ) ?></p>
			<div class="player-wrap">
				<div id="player">Для просмотра этого видео нужна поддержка Flash player 8+ и JavaScript в вашем браузере.</div>
			</div>
			<?php 
			$this->inlineScript()->appendScript('var params = { allowScriptAccess: "always", allowfullscreen:"true" };
			    var attrs = { id: "mytplayer" };
			    swfobject.embedSWF("http://www.youtube.com/v/'.$this->main_video->getVideoId().'?enablejsapi=1&playerapiid=ytplayer&version=3&allowfullscreen=true",
			    	"player",
			    	"460",
			    	"258",
			    	"8",
			    	null,
			    	null,
			    	params,
			    	attrs);');
			echo $this->inlineScript();
			?>
			
			<?php 
			/*
			$tags = $this->main_video->getVideoTags();
			
			if (count($tags)) {
			    ?>
			    <div class="taglist title">
					Темы этого видео
				</div>
			    <ul class="taglist">
			    <?php 
				$i=0;
				do {
					$t = trim($tags[$i]);
					if (!empty($t)) {
						$t = $this->safeTag($t);
						?>
					<li class="btn btn-mini">
						<a href="/видео/тема/<?php echo $this->safeTag($tags[$i]); ?>?p=<?php echo base64_encode($tags[$i]) ?>" title="Видео про <?php echo $this->escape($tags[$i]); ?>" target="_blank"><?php echo $tags[$i] ?></a>
					</li>
						<?php 
					}
					unset($tags[$i]);
					$i++;
				} while (count($tags)>0);
				?>
				</ul>
				<?php 
			 } */ ?>
			
	
	
	</div>
	
	<div class="related">
	<?php 
	//$grid_columns = 1;
	//$col_width_pct = floor(100/$grid_columns)-1;
	//$amount=(int)Zend_Registry::get('site_config')->videos->related->get('amount');
	foreach ($this->related_videos as $v) {
		
		$current = $v;
		
		if (!preg_match('/\p{Cyrillic}+/ui', $current->getVideoTitle()))
		continue;
		
		?>
		<div class="videocell">
			
			<?php 
			$title = $current->getVideoTitle();
			$vid   = Xmltv_Youtube::genRtvgId( $current->getVideoId() );
			$alias = Xmltv_Youtube::videoAlias( $title);
			?>
			
			<h3 class="title">
				<a href="<?php echo $this->url( array('alias'=>$alias, 'id'=>$vid), 'default_videos_show-video' )  ?>" title="Смотреть онлайн <?php echo $title ?>" target="_blank"><?php echo $title ?></a></h2>
			</h3>
		
			<div class="videothumb">
				
				<?php 
				try {
					$videoThumbnails = $current->getVideoThumbnails();
				} catch (Exception $e) {
					echo $e->getMessage();
				}
				$k=0;
				foreach($videoThumbnails as $videoThumbnail) {
					if ($videoThumbnail['width'] >= 200) {
						
						?>
						<a class="imagelink" href="<?php echo $this->url( array('alias'=>Xmltv_Youtube::videoAlias( $title), 'id'=>$vid), 'default_videos_show-video' ) ?>">
							<img src="<?php echo $videoThumbnail['url'] ?>" width="240" alt="<?php echo $title ?>" />
						</a>
						
						<?php 
						break;
					}
					$k++;
				}
				
				?>
				
				<p class="viewcount">Посмотрели: <?php echo number_format( (int)$current->getVideoViewCount(), 0 ) ?></p>
				
				<p class="cat">
					<?php 
					$catEn = $current->getVideoCategory();
					$catRu = Xmltv_Youtube::getCatRu($catEn); 
					if ($catRu==$catEn) {
					?>
					Категория: <?php echo $catEn; ?>
					<?php 
					} else {
						?>
					Категория: <a href="/каналы/<?php echo Xmltv_String::strtolower( $catRu ) ?>" target="_blank" title="<?php $catRu ?> каналы телепрограмма"><?php echo $catRu; ?></a>
						<?php 
					}?>
					 
				</p>
				
				<p class="date">
					<?php $date = new Zend_Date ( $current->getUpdated() ); ?>
					Добавлено <?php echo $date->toString('d MMM YYYY');  ?>
				</p>
				
			</div>
				
			<div class="videoinfo">
				
				
				
				<?php
				$desc = $this->truncateString( $current->getVideoDescription(), 35, 'words' );
				if (!empty($desc)) {
					?>
				<p class="desc">
					<?php echo $desc ?>
				</p>
					<?php 
				} ?>
				
			</div>
			
			<?php 
			/*
			$tags = $current->getVideoTags();
			//var_dump($tags);
			if (count($tags)) {
				?>
				<ul class="tags">
				<?php 
				$i=0;
				do {
					$t = trim($tags[$i]);
					if (!empty($t)) {
						$t = $this->safeTag($t);
						?>
						<li class="btn btn-mini">
							<a href="/видео/тема/<?php echo $this->safeTag($tags[$i]); ?>?p=<?php echo urlencode ( base64_encode( $tags[$i] ) ) ?>" title="Видео про <?php echo $this->safeTag($tags[$i]); ?>" target="_blank"><?php echo $tags[$i] ?></a>
						</li>
						<?php 
					}
					unset($tags[$i]);
					$i++;
				} while (count($tags)>0);
				?>
				</ul>
				<?php 
			 }*/ ?>
			
			
		</div>
		<?php 
		} ?>
		
	</div>
	
</div>