<?php 
$this->headTitle( sprintf("Онлайн-видео: %s", $this->tag ));
?>


<h1>
	<?php printf("10 новых видео на тему «%s»", $this->tag) ?>
</h1>

<?php

$ytConfig = array(
	'max_results'=>10,
	'safe_search'=>'none',
	'order'=>'published'
);

//$ytConfig['debug']=true;

$yt = new Xmltv_Youtube( $ytConfig );

if (strstr($this->tag, ' ')) {
	$queryData = explode(' ', $this->tag);
} else {
	$queryData = array($this->tag);
}
$videos = $yt->fetchVideos( $queryData );

?>


<?php if (!count( $videos) ) { ?>
<p>К сожалению на эту тему видео не найдено</p>
<?php 
} else {
	//var_dump($videos->getEntry());
	$k=0;
	for ($i=1; $i<count($videos); $i++) {
		
		$videoEntry = $videos->offsetGet($i);
		if (!is_a($videoEntry, 'Zend_Gdata_YouTube_VideoEntry'))
			continue;
		
		if ($k==0)
			$this->headMeta()->setName( 'description', $this->truncateString( htmlspecialchars( $videoEntry->getVideoDescription()), 12, 'words'));
		
		$videoProps = array();
		
		$videoProps['title'] = trim( $videoEntry->getVideoTitle() );
		$videoProps['alias'] = Xmltv_Youtube::videoAlias( $videoProps['title'] );
		$videoProps['id'] = Xmltv_Youtube::videoId($videoEntry->getVideoId());
		
		$videoProps['link_category'] = false;
		$videoProps['category'] = $videoEntry->getVideoCategory();
		$cat = Xmltv_Youtube::getCatRu( $videoProps['category'] ); 
		if ($cat != $videoProps['category']) {
			$videoProps['category'] = $cat;
			$videoProps['link_category'] = true;
		}
		
		
		$d = new Zend_Date($videoEntry->getUpdated(), Zend_Date::ISO_8601);
		$d->addHour(3);
		$videoProps['date'] = Xmltv_String::ucfirst( $d->toString("EEEE, d MMM YYYY") );
		
		$videoProps['desc'] = Xmltv_Youtube::processLinks( $videoEntry->getVideoDescription(), $videoProps['title'], 'convert' );
		
		$videoProps['tags'] = array();
		try {
			$videoProps['tags'] = $videoEntry->getVideoTags();
		} catch (Exception $e) {
			echo $e->getMessage();
		}
		
		try {
			$videoThumbnails = $videoEntry->getVideoThumbnails();
			foreach($videoThumbnails as $videoThumbnail) {
				if (stristr($videoThumbnail['url'], 'mqdefault')) {
					$videoProps['thumb'] = $videoThumbnail;
				}
			}
		} catch (Exception $e) {
			echo $e->getMessage();
		}
		
		
		//var_dump($videoProps);
		//die(__FILE__.': '.__LINE__);
		?>
		
		<div class="videocell">
			
			<h3 class="title">
				<a href="/видео/онлайн/<?php echo $videoProps['alias'] ?>/<?php echo $videoProps['id'] ?>">
					<?php echo $videoProps['title'] ?>
				</a>
			</h3>
			
			<a class="imagelink" href="/видео/онлайн/<?php echo $videoProps['alias'] ?>/<?php echo $videoProps['id'] ?>">
				<img width="<?php echo $videoProps['thumb']['width'] ?>" src="<?php echo $videoProps['thumb']['url'] ?>" alt="<?php echo $videoProps['title'] ?>" />
			</a>
			
			<p class="cat">Категория: 
				<?php if ($videoProps['link_category']===true) : ?>
				<a href="/каналы/<?php echo Xmltv_String::strtolower( $videoProps['category'] ) ?>" target="_blank" title="<?php echo $videoProps['category'] ?> каналы телепрограмма"><?php echo $videoProps['category'] ?></a>
				<?php else: ?>
				<?php echo $videoProps['category'] ?>
				<?php endif; ?>
			</p>
			<p class="pub">
				<?php echo $videoProps['date'] ?>
			</p>
			
				
				
			<?php
			if (!empty($videoProps['desc'])) {
				?>
			<p class="desc">
				<?php echo $this->truncateString( $videoProps['desc'], 50, 'words') ?>
			</p>
				<?php 
			} ?>
			
		
			<ul class="tags">
			<?php 
			foreach ($videoProps['tags'] as $tag) {
				$safeTag = Xmltv_String::strtolower( $this->safeTag($tag) );
				$fullTag = $this->escape($tag);
				?>
				<li>
					<a class="badge badge-important" href="/видео/тема/<?php echo $safeTag ?>?p=<?php echo urlencode( base64_encode( $fullTag )) ?>" target="_blank" title="Онлайн-видео на тему <?php echo $fullTag ?>">
						<?php echo $fullTag ?>
					</a>
				</li>
			<?php 
			} ?>
			</ul>
				
			
			
		</div>
	<?php 
	}
}
?>
