<?php
/**
 * Administrator control panel layout
 * 
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: admin.phtml,v 1.6 2013-02-15 00:44:02 developer Exp $
 *
 */
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8'); 
$this->headScript()->setAllowArbitraryAttributes(true);
$this->jQuery()
	->enable()
	->setVersion('1.7.1')
	->setUiVersion('1.8.18')
	->addStylesheet('https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/ui-lightness/jquery-ui.css')
	->uiEnable();

$this->headLink( array('rel'=>'stylesheet/less', 'href'=>$this->baseUrl('css/template.less')), 'APPEND');

$request    = Zend_Controller_Front::getInstance()->getRequest();
$controller = $request->getControllerName();
$mainNav    = $this->mainNav($controller);
?>
<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
<?php 
echo $this->headMeta();
echo $this->headTitle();
echo $this->jQuery();
echo $this->headScript()
	->prependFile($this->baseUrl().'/js/bootstrap.min.js')
	->prependFile($this->baseUrl($this->baseUrl('js/less.min.js')));
echo $this->headLink()
	->prependStylesheet($this->baseUrl().'/css/base.css');
echo $this->headStyle();
?>
</head>
<body>
<div class="container">
	<div id="nav">
		<?php echo $mainNav; ?>
	</div>
	<h4>
		APPLICATION_ENV: <?php echo APPLICATION_ENV ?><br />
		memory_limit: <?php echo ini_get('memory_limit') ?><br />
		error_reporting: <?php echo ini_get('error_reporting') ?><br />
		display_errors: <?php echo ini_get('display_errors') ?><br />
	</h4>
	<div class="span12">
		<?php echo $this->layout()->content; ?>
	</div>
	
</div>
<?php echo $this->inlineScript(); ?>
</body>
</html>