<?php
/**
 * Common layout
 * 
 * @author  Antony Repin
 * @package rutvgid
 * @version $Id: layout.phtml,v 1.29 2013-03-05 06:53:19 developer Exp $
 *
 */

$pageClass   = isset($this->pageclass) && !empty($this->pageclass) ? ' '.(string)$this->pageclass : '' ;
$isFrontpage = trim($pageClass)=='frontpage' ? true  : false ;

$this->maincontent_width = 6;
if ($this->hide_sidebar=='left'){
	$this->maincontent_width = 8;
}
if ($this->hide_sidebar=='right'){
	$this->maincontent_width = 10;
}

$this->headMeta()
	->prependHttpEquiv('Content-Type', 'text/html;charset=utf-8');

$this->headLink( array('rel'=>'stylesheet/less', 'href'=>$this->baseUrl('css/template.less')), 'APPEND');
$this->headLink()
	->prependStylesheet( $this->baseUrl('css/base.css'))
	->appendStylesheet( $this->baseUrl('js/tip/jquery.tooltip.css'));

/*
 * Check browser
 */
$browser = $this->userAgent()->getUserAgent();
$browserMsie = false;
if (strstr($browser, 'MSIE')) {
	$browserMsie = true;
	$this->headLink()
		->appendStylesheet($this->baseUrl('css/ie.css'))
		->appendStylesheet($this->baseUrl('css/fonts-ie.css'));
}

$this->headTitle()
	->setSeparator(' :: ');


$this->jQuery()->enable() //enable jquery ;
	//->setCdnSsl(true) if need to load from ssl location
	->setVersion('1.8.3') //jQuery version, automatically 1.5 = 1.5.latest
	->setUiVersion('1.8.18') //jQuery UI version, automatically 1.8 = 1.8.latest
	->uiEnable();

$this->headScript()
	->setAllowArbitraryAttributes(true)
	->prependFile( $this->baseUrl( $this->baseUrl( 'js/less.min.js' )))
	//->appendFile( $this->baseUrl( 'js/realt.js' ))
	->appendFile( 'http://yandex.st/share/share.js' )
	->appendFile( '//vk.com/js/api/openapi.js?75' );

if (APPLICATION_ENV=='development'){
    $this->headScript()->prependFile( $this->baseUrl( 'js/bootstrap.js' ));
} else {
    $this->headScript()->prependFile( $this->baseUrl( 'js/bootstrap.min.js' ));
}

$this->inlineScript()
->appendScript( Rtvg_Compressor_JSMin::minify('VK.init({apiId: 2963750, onlyWidgets: true});
$("a[class^=\'mg_ad\']").remove();
jQuery(document).ready(function(){
	$("#footer .counter_logo").css({ display: "none" });
	//if  ($("#col_r .da_adp_links")) { $("#col_r .da_adp_links").css({ display: "none" }); }
});'));

if (!$isFrontpage){
    $this->inlineScript()
    	->appendScript('VK.Widgets.Group("vk_groups", {mode: 0, width: "350", height: "290" }, 27716041);');
}

/*
 * #### Header ####
 */
$this->placeholder('header')->set( $this->partial('partials/header.phtml', array(
		'pageclass'=>$this->pageclass,
		'nav_html'=>$this->navigation()->menu()->renderMenu( Zend_Registry::get('FpMenu'), array('ulClass' => 'nav')),
)));

/*
 * #### Main content ####
 */
$this->placeholder('maincontent')->set( $this->layout()->content );

/*
 * #### Featured channels list ####
 */
if ($pageClass=='show-video'){
    $this->placeholder('featured_channels')->set( 
    	$this->partial('partials/featured-channels.phtml', array(
    		'list'=>$this->featured_channels)) );
}

/*
 * #### Left Sidebar ####
 */
$this->placeholder('sidebar_left')->set( $this->partial('partials/sidebar-left.phtml', array(
	'top_programs'=>$this->top_programs,
	'cats'=>$this->channels_cats,
	'channel'=>$this->channel 
)));

/*
 * #### Right Sidebar ####
 */
if ($this->current_program) $sidebarConf['program'] = $this->current_program;
$this->placeholder('sidebar_right')->set( $this->partial( 'partials/sidebar-right.phtml', array(
	'videos'=>$this->sidebar_videos,
	'channel'=>$this->channel,
)));

/*
 * #### Footer ####
 */
$this->placeholder('footer')->set( $this->partial('partials/footer.phtml', array()) );

/* 
$this->headStyle()
	->appendStyle("");
 */

if ( APPLICATION_ENV!='testing' && !$isFrontpage) {
	$this->inlineScript()
	//->appendFile("http://code.directadvert.ru/show.cgi?adp=85979&div=DIV_DA_85979")  //directadvert rollin
	->appendFile("http://code.directadvert.ru/show.cgi?adp=85753&div=DIV_DA_85753");  //directadvert right sidebar
}
?>

<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xml:lang="ru" lang="ru">
<head>
<?php 
echo $this->headTitle(), PHP_EOL;
echo $this->headMeta(), PHP_EOL;
echo $this->jQuery();
echo $this->headLink(), PHP_EOL;
echo $this->headScript(), PHP_EOL;
?>
<?php 
if (APPLICATION_ENV=='production') {
?>
<script type="text/javascript">
<?php echo Rtvg_Compressor_JSMin::minify('new Image().src = "//counter.yadro.ru/hit?r"+
escape(document.referrer)+((typeof(screen)=="undefined")?"":
";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
";h"+escape(document.title.substring(0,80))+
";"+Math.random();'); ?>
</script>
<script type="text/javascript">
<?php echo Rtvg_Compressor_JSMin::minify("var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-778789-8']);

(function() {
  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();"); ?>
</script>
<?php
} ?>
<script type="text/javascript">
<?php 
$source = new Rtvg_Ad_Script(null, array(
	'load_folder'=>true,
	'folder'=>ROOT_PATH.'/public/js/ss/wizard',
));
echo Rtvg_Compressor_JSMin::minify( $source->pickRandom() );

$source = new Rtvg_Ad_Script(null, array(
	'load_folder'=>true,
	'folder'=>ROOT_PATH.'/public/js/ss/realtraf',
));
echo Rtvg_Compressor_JSMin::minify( $source->getFirst() );

echo Rtvg_Compressor_JSMin::minify("(function() {
		var cx = '006526203727824860247:vdzpxf_4n5a';
		var gcse = document.createElement('script'); gcse.type = 'text/javascript'; gcse.async = true;
		gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
		'//www.google.ru/cse/cse.js?cx=' + cx;
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(gcse, s);
})();")
?>
</script>
</head>
<body>
	
	<div class="row-fluid" id="header">
		<?php echo $this->placeholder('header'); ?>
	</div>
	
	<?php  if (!$isFrontpage): ?>
	<div class="row-fluid">
		<gcse:searchresults></gcse:searchresults>
	</div>
	<?php endif; ?>
	
	<div id="content" class="row-fluid<?php echo $pageClass; ?>">
		
		<?php 
		if (count($this->messages)) {
			foreach ($this->messages as $text) {
				if (is_array($text)) {
					foreach ($text as $string) {
						echo $this->showMessage( $string );
					}
				} else {
					echo $this->showMessage( $text );
				}
			}
		}
		?>
		
		<?php 
		if ($isFrontpage) {
			?>
		<div class="span12" id="maincontent">
			<?php echo $this->placeholder('maincontent'); 
			?>
		</div>
			<?php 
		} else {
			?>
		
			<?php if (!($this->hide_sidebar=='left')): ?>
			<div class="span2" id="col_l">
				<?php echo $this->placeholder('sidebar_left'); ?>
			</div>
			<?php endif; ?>
			
			<div class="span<?php echo $this->maincontent_width ?>" id="maincontent">
				<?php echo $this->placeholder('maincontent'); ?>
			</div>
					
			<?php if (!($this->hide_sidebar=='right')): ?>
			<div class="span4" id="col_r">
				<?php echo $this->placeholder('sidebar_right'); ?>
			</div>
			<?php endif; ?>
		
		<?php 
		} ?>
		
	</div>
	
	<?php 
	/*
	 * Featured channels links
	 */
	if ($pageClass=='show-video'){
		$fChannels = $this->placeholder('featured_channels');
		if (!empty($fChannels)) { ?>
		<div id="featuredchannels" class="row-fluid">
			<?php echo $fChannels; ?>
		</div>
		<?php 
		} 
	} ?>
	
	<div class="row-fluid" id="footer">
		<?php echo $this->placeholder('footer'); ?>
	</div>


<?php 
if (APPLICATION_ENV=='production'){
	?>
	
	<script type="text/javascript">
	(function (d, w, c) {
	    (w[c] = w[c] || []).push(function() {
	        try {
	            w.yaCounter16053280 = new Ya.Metrika({id:16053280, enableAll: true, webvisor:true});
	        } catch(e) {}
	    });
	    
	    var n = d.getElementsByTagName("script")[0],
	        s = d.createElement("script"),
	        f = function () { n.parentNode.insertBefore(s, n); };
	    s.type = "text/javascript";
	    s.async = true;
	    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";
	
	    if (w.opera == "[object Opera]") {
	        d.addEventListener("DOMContentLoaded", f);
	    } else { f(); }
	})(document, window, "yandex_metrika_callbacks");
	</script>
	<noscript><div><img src="//mc.yandex.ru/watch/16053280" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
	<?php 
}
?>

<?php echo $this->inlineScript(); ?>

<?php 
/*
 * Marketgid code
 */

?>
<?php /*<script type="text/javascript">
var MarketGidDate = new Date();
document.write('<scr'+'ipt type="text/javascript" '
+'src="http://jsc.dt00.net/r/u/rutvgid.ru.35536.js?t='+MarketGidDate.getYear()+MarketGidDate.getMonth()+MarketGidDate.getDay()+MarketGidDate.getHours() + '" charset="utf-8" ></scr'+'ipt>');
</script>
*/ ?>

</body>
</html>