<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8'); 
$this->headScript()->setAllowArbitraryAttributes(true);
$this->jQuery()->enable()//enable jquery ; ->setCdnSsl(true) if need to load from ssl location
		     ->setVersion('1.7.1')//jQuery version, automatically 1.5 = 1.5.latest
		     ->setUiVersion('1.8.18')//jQuery UI version, automatically 1.8 = 1.8.latest
		     //->addStylesheet('https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/ui-lightness/jquery-ui.css')//add the css
		     ->uiEnable();//enable ui
?>
<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
<?php 
echo $this->headMeta();
echo $this->headTitle();
echo $this->jQuery();
echo $this->headScript();
	//->prependFile($this->baseUrl().'/js/bootstrap-dropdown.js')
	//->prependFile($this->baseUrl().'/js/bootstrap-collapse.js')
	//->prependFile($this->baseUrl().'/js/bootstrap.min.js');
echo $this->headLink()
	->prependStylesheet($this->baseUrl().'/css/template.css')
	->prependStylesheet($this->baseUrl().'/css/bootstrap.css');
?>
<style type="text/css">
#maincontent { overflow:hidden; }
[class*="span"] { margin-left: 20px; }
</style>
</head>
<body>
<div class="container">
	<div class="span12">
		<div class="span2" id="col_l">&nbsp;</div>
		<div class="span6" id="maincontent">
			<?php echo $this->layout()->content; ?>
		</div>
		<div class="span4" id="col_r">&nbsp;</div>
	</div>
</div>
</body>
</html>