<?php 
/**
 * Отдельное видео на странице дневного расписания
 * 
 * @author  Antony Repin
 * @version $Id: day-video.phtml,v 1.3 2013-04-06 22:35:04 developer Exp $
 */
?>

<?php 
$videoTitle = $this->escape( $this->item['title'] );
if ($this->show_title===true) { ?>
<h4 class="title"><?php echo $videoTitle; ?></h4>
<?php } ?>

<p class="video">
	<?php 
	$videoAlias = $this->escape( $this->item['alias'] );
	$videoDesc  = $this->escape( $this->item['desc'] );
	$videoId	= $this->escape( $this->item['rtvg_id'] );
	$videoUrl   = $this->url( array('alias'=>$videoAlias, 'id'=>$videoId), 'default_videos_show-video' );
	$imgAttrSrc = (isset($this->random_image) && $this->random_image===true) ? 
		$this->item['thumbs'][mt_rand(0, count($this->item['thumbs'])-1)]['url'] :
		$this->item['thumbs'][0]['url'] ;
	
	if(!empty($videoDesc)) {
		echo $videoDesc;
	}
	
	$thW = (int)Zend_Registry::get('site_config')->videos->listing->get('thumb_width'); ?>
	<a href="<?php echo $videoUrl ?>" title="<?php printf("Видео %s онлайн", $videoTitle); ?>">
		<img src="<?php echo $imgAttrSrc; ?>" alt="<?php echo $videoTitle ?>" />
	</a>
	
</p>
		
