<?php 
/**
 * Partial to render ListingsController::programDayAction() listing item
 * 
 * @author  Antony Repin <egeshisolutions@gmail.com>
 * @version $Id: day-item.phtml,v 1.2 2013-03-14 06:09:55 developer Exp $
 *
 */

$newDate=null;
foreach ($this->items as $single) {
    
    if (APPLICATION_ENV=='development'){
    	//var_dump($single);
    	//die(__FILE__.': '.__LINE__);
    }
    
    $programTitle = $this->escape( $single['title'] );
    $programAlias = $this->escape( $single['alias'] );
    $channelTitle = $this->escape( $single['channel_title'] );
    $channelAlias = $this->escape( $single['channel_alias'] );
    $category = $this->escape( $single['category_title_single'] );
    
    if (null === $newDate || ($single['start']->toString("DDD") !== $newDate)) {
        $day = Xmltv_String::ucfirst( $single['start']->toString( 'EEEE' ));
        $startDay  = $single['start']->toString( 'd MMMM');
        $startTime = $single['start']->toString( 'H:mm' );
        $dateString = sprintf( '<span class="label label-info">%s</span> %s в %s', $day, $startDay, $startTime );
    } else {
        $dateString = ' в <u>'.$this->item['start']->toString( 'H:mm' ).'</u>';
    }
    
    $linkAttrHref = $this->url( array(
		'channel'=>$channelAlias,
		'date'=>$single['start']->toString("dd-MM-YYYY")), 'default_listings_day-date' ).'?ts='.$single['start']->toString("U");
    
    $linkAttrTitle = sprintf("«%s» %s на канале «%s»", $programTitle, $single['start']->toString( 'dd MMM'), $channelTitle);
    $live = isset($single['live']) && ((bool)$single['live'] === true) ? '<br />в прямом эфире' : '' ;
    $premiere = isset($single['premiere']) && ((bool)$single['premiere'] === true) ? '<br />Премьера' : '' ;
?>
<p>
	<?php echo $dateString; ?>
	<?php echo $category; ?> 
	<a href="<?php echo $linkAttrHref ?>" title="<?php echo $linkAttrTitle ?>" target="_blank">
		<em><?php echo $programTitle ?></em>
	</a> на канале <?php echo $channelTitle ?>
	<?php echo $live ?>
	<?php echo $premiere ?>
</p>
<?php 
} ?>