<?php 
/**
 * Передачи сегодня
 * 
 * @author  Antony Repin
 * @version $Id: programlist.phtml,v 1.5 2013-04-11 05:21:11 developer Exp $
 *
 */

$channelTitle = $this->escape( $this->channel['title'] );
$channelAlias = $this->escape( $this->channel['alias'] );

$this->headMeta()->setName('title', sprintf ('«%s» онлайн, %s', $channelTitle, $this->listingDate->toString( 'EEEE, d MMMM YYYY' )));
$this->headTitle( sprintf ('Передачи сейчас', $channelTitle ));
$this->inlineScript()->appendScript("$(function(){ $('.iconLive').tooltip() });");

//Generate keywords
$kw = array(
    $channelTitle,
    'смотреть онлайн',
    'торрент тв'
 );
if (!empty($this->items)) {
	foreach ($this->items as $p) {
        if (count($kw)<5) {
			if (!in_array($p['title'], $kw))
				$kw[]= Xmltv_String::strtolower( htmlspecialchars( $p['title'], ENT_QUOTES, 'utf-8' ) );
		}
	}
}
$this->headMeta()->setName('keywords', implode(',', $kw) );

?>

<div id="programlist" class="row-fluid">

    <?php 
    $pc=0;
    foreach ($this->items as $k=>$prog) {

        if ($this->is_today){
            $active = @$prog['now_showing']===true ? ' active' : '' ;
        } else {
            $active = $pc==0 ? ' active' : '' ;
        }
        
        switch ($k){
            case 0:
                $timespan = 'Сейчас';
                $bg = "#FFCC00";
                $showRating = true;
            break;
            case 1:
                $timespan = 'Далее';
                $bg = "#BABABA";
                $showRating = true;
            break;
            case 2:
                $timespan = 'Затем';
                $bg = "#FFFFFF";
                $showRating = true;
                break;
            case 3:
                $timespan = 'После';
                $bg = "#FFFFFF";
            break;
            default: break;
        }
        
        //Item width
        $spans = 3;
        if (count($this->items)==3){
            $spans = 4;
        } elseif (count($this->items)==2){
            $spans = 6;
        } elseif (count($this->items)==1){
            $spans = 12;
        }
        
        ?>

    <div class="item<?php echo $active; ?> span<?php echo $spans ?>">

        <?php if ($this->is_today): ?>
        <span class="label"><?php echo $timespan; ?></span>
        <?php endif; ?>

        <span itemscope itemtype="http://schema.org/Event" class="start label label-info">
            <time itemprop="startDate" datetime="<?php echo $prog['start']->toString(Zend_Date::ISO_8601) ?>">
                <?php echo $prog['start']->toString('HH:mm') ?>
            </time>
        </span>

        <?php if (isset($prog['live']) && ($prog['live']===true)): ?>
        <img src="<?php echo $this->baseUrl('images/icons/live.png'); ?>" class="iconLive" title="В прямом эфире" />
        <?php endif; ?>


        <h3>
            <a href="<?php echo $this->url( array(
                'channel'=>$channelAlias,
                'alias'=>$prog['alias']), 'default_listings_broadcast-week' ); ?>"
                title="Расписание <?php echo $prog['title'] ?> на неделю"
                target="_self">
                <?php echo $prog['title']; ?>
            </a>
        </h3>


        <?php if (isset($prog['sub_title']) && !empty($prog['sub_title'])) : ?>
        <p class="subtitle"><?php echo $prog['sub_title'] ?></p>
        <?php endif; ?>


        <?php if (isset($prog['rating']) && $prog['rating']>0) : ?>
        <p class="age-rating">Возрастной рейтинг: 
            <span class="label label-age-rating"><?php echo $prog['rating'] ?>+</span>
        </p>
        <?php endif; ?>


        <ul class="nav nav-pills nav-list program-links">
            <li>
                <a href="<?php echo $this->url( array(
                    'alias'=>$prog['alias'],
                    'channel'=>$channelAlias,
                    'timespan'=>'сегодня'), 'default_listings_broadcast-day'); ?>" title="<?php echo $prog['title'] ?> сегодня">
                    <?php printf('%s, <strong>%s</strong> сегодня', $channelTitle, $prog['title']) ; ?>
                </a>
            </li>
            
            <?php 
            if (isset($prog['category_title']) && !empty($prog['category_title'])) {
                if ($this->is_today===true){
                ?>
            <li>
                <a href="<?php echo $this->url( array(
                    'category'=>$prog['category_alias'],
                    'timespan'=>'неделя'), 'default_listings_category'); ?>" title="Передачи на неделе">
                    <strong><?php echo $prog['category_title']; ?></strong> на этой неделе
                </a>
            </li>
            <?php } ?>
            <li><a href="<?php echo $this->url( array(
                'category'=>$prog['category_alias'],
                'timespan'=>'сегодня'), 'default_listings_category'); ?>" title="Передачи сегодня">
                <strong><?php echo $prog['category_title']; ?></strong> сегодня
            </a></li>
        <?php } ?>
        </ul>




        <?php 
        if (count($this->listing_videos)) {
            if (array_key_exists( $prog['hash'], $this->listing_videos)){
                echo $this->partial( 'listings/partials/day-video.phtml', array(
                    'item' => $this->listing_videos[$prog['hash']],
                    'show_image'   => true,
                    'random_image' => false,
                ));
            }
        } ?>



        <?php 
        if ( isset($prog['desc']) && !empty($prog['desc'])) { ?>
        <div class="wrapper">
            <p class="description">
                <?php echo $this->truncateString( $this->escape( $prog['desc'] ), 50, 'words', '.' ); ?>
            </p>
        </div>
        <?php } ?>

    </div>

    <?php 
        $pc++;
    }
    ?>


</div>


<ul id="daynav" class="nav nav-pills pull-right">
    <li>
        <?php 
        $d = new Zend_Date($this->listingDate->toString('U'), 'U');
        $d->subDay(1);
        ?>
        <a href="<?php echo $this->url(array('channel'=>$channelAlias, 'date'=>$d->toString('dd-MM-YYYY')), 'default_listings_day-date') ?>"
            class="btn btn-small"
            title="Программа <?php echo $channelTitle ?> на <?php echo $d->toString('dd-MM-YYYY') ?>">Вчера</a>
    </li>
    <li>
        <?php 
        $d = new Zend_Date($this->listingDate->toString('U'), 'U');
        $d->addDay(1);
        ?>
        <a href="<?php echo $this->url(array( 'channel'=>$channelAlias, 'date'=>$d->toString('dd-MM-yyyy')), 'default_listings_day-date') ?>"
            class="btn btn-small"
            title="Программа <?php echo $channelTitle ?> на <?php echo $d->toString('dd-MM-yyyy') ?>">Завтра</a>
    </li>

</ul>
