<?php 
/**
 * Передачи сегодня
 * 
 * @author  Antony Repin
 * @version $Id: programlist.phtml,v 1.3 2013-04-03 18:18:05 developer Exp $
 *
 */

$channelTitle = $this->escape( $this->channel['title'] );
$channelAlias = $this->escape( $this->channel['alias'] );
$channelCat   = $this->escape( $this->channel['cat_title'] );
?>

<div id="programlist" class="container-fluid">
	<div class="pull-left span9">
	<?php 
	$pc=0;
	foreach ($this->items as $k=>$prog) {
		
		if ($this->is_today){
			$active = $prog['now_showing']===true ? ' active' : '' ;
		} else {
			$active = $pc==0 ? ' active' : '' ;
		}
		
		if (APPLICATION_ENV=='development'){
			//var_dump($k);
			//var_dump($active);
			//var_dump($prog);
			//die(__FILE__.': '.__LINE__);
		}
		
		switch ($k){
			case 0:
				$timespan = '';
				$bg = "#FFCC00";
				$showRating = true;
			break;
		   	case 1:
				$timespan = 'Далее';
				$bg = "#BABABA";
				$showRating = true;
			break;
			case 2:
				$timespan = 'Затем';
				$bg = "#FFFFFF";
				$showRating = true;
				break;
			case 3:
			    $timespan = 'После';
				$bg = "#FFFFFF";
			break;
			default: break;
		}
		?>
		
	<div class="item<?php echo $active; ?> span3">
		
		<span class="label"><?php echo $timespan; ?></span>
		<span class="start label label-info"><?php echo $prog['start']->toString('HH:mm') ?></span>
		
		<?php if (isset($prog['live']) && ($prog['live']===true)): ?>
		<img src="<?php echo $this->baseUrl('images/icons/live.png'); ?>" />
		<?php endif; ?>
		
		
		<h3>
			<a href="<?php echo $this->url( array(
				'channel'=>$channelAlias,
				'alias'=>$prog['alias']), 'default_listings_program-week' ); ?>"
				title="Расписание <?php echo $prog['title'] ?> на неделю"
				target="_self">
				<?php echo $prog['title']; ?>
			</a>
		</h3>
		
		
		<?php if (isset($prog['sub_title']) && !empty($prog['sub_title'])) : ?>
		<p class="subtitle"><?php echo $prog['sub_title'] ?></p>
		<?php endif; ?>
		
		
		<?php if (isset($prog['rating']) && $prog['rating']>0) : ?>
		<p class="age-rating">Возрастной рейтинг: 
			<span class="label label-age-rating"><?php echo $prog['rating'] ?>+</span>
		</p>
		<?php endif; ?>
		
		
		<ul class="nav nav-pills nav-list program-links">
			<li><a href="<?php echo $this->url( array(
				'alias'=>$prog['alias'],
				'channel'=>$channelAlias,
				'timespan'=>'сегодня'), 'default_listings_program-day'); ?>" title="<?php echo $prog['title'] ?> сегодня">
				<?php printf('%s, <strong>%s</strong> сегодня', $channelTitle, $prog['title']) ; ?>
			</a></li>
			<?php if (isset($prog['category_title']) && !empty($prog['category_title'])): ?>
			<li><a href="<?php echo $this->url( array(
				'category'=>$prog['category_alias'],
				'timespan'=>'неделя'), 'default_listings_category'); ?>" title="Передачи на неделе">
				<strong><?php echo $prog['category_title']; ?></strong> на этой неделе
			</a>
			</li>
			<li><a href="<?php echo $this->url( array(
				'category'=>$prog['category_alias'],
				'timespan'=>'сегодня'), 'default_listings_category'); ?>" title="Передачи сегодня">
				<strong><?php echo $prog['category_title']; ?></strong> сегодня
			</a></li>
		<?php endif; ?>
		</ul>
		
		
		
		
		
		
		
		
		<?php 
		/*
		 * Видео
		*/
		if (count($this->listing_videos)) {
		    if (array_key_exists( $prog['hash'], $this->listing_videos)){
				echo $this->partial( 'listings/partials/day-video.phtml', array(
					'item' => $this->listing_videos[$prog['hash']],
					'show_image'   => true,
					'random_image' => false,
				));
			}
		} ?>
		
		
		
		<?php 
		/*
		 * Описание программы
		 */
		if ( isset($prog['desc']) && !empty($prog['desc'])) { ?>
		<p class="desc">
			<?php echo $this->truncateString( $this->escape( $prog['desc'] ), 30, 'words' ); ?>
		</p>
		<?php } ?>
		
		
		<?php /* 
		if (isset($prog['actors']) && !empty($prog['actors'])) { 
			if (APPLICATION_ENV=='development'){
			    var_dump($prog['actors']);
				die(__FILE__.': '.__LINE__);
			}
			?>
		<p>В ролях:
			<ul class="persons btn-group">
				<?php foreach ($prog['actors'] as $p): ?>
				<li class="btn btn-mini">
					<?php echo $p['complete_name'] ?>
				</li>
				<?php endforeach; ?>
			</ul>
		</p>
		<?php } */ ?>
		
		<?php /* if (isset($prog['directors']) && !empty($prog['directors'])): ?>
		<p>Режиссер:
			<ul class="persons btn-group">
				<?php foreach ($prog['directors'] as $p): ?>
				<li class="btn btn-mini">
					<?php echo $p['complete_name'] ?>
				</li>
				<?php endforeach; ?>
			</ul>
		</p>
		<?php endif; */ ?>
		
	</div>
	
	<?php 
		$pc++;
	}
	?>
	</div>
	
	<div class="span3">
		<?php echo $this->adCode(array(
			'w'=>300,
			'h'=>300,
			'type'=>'cpa',
			'output'=>'stack',
			'amt'=>2,
		)); ?>
	</div>
	
</div>