<?php
/**
 * Передачи сегодня в виде таблицы
 * 
 * @author  Antony Repin
 * @version $Id: programlist.phtml,v 1.3 2013/04/03 18:18:05 developer Exp $
 *
 */


$channelTitle = $this->escape( $this->channel['title'] );
$channelAlias = $this->escape( $this->channel['alias'] );


$this->headMeta()->setName('title', sprintf ('Канал «%s», %s', $channelTitle, $this->listingDate->toString('EEEE, d MMMM YYYY')));
$this->headTitle( sprintf ('Все передачи', $channelTitle ));

//Generate keywords
$kw = array($channelTitle, $this->listingDate->toString('d MMMM YYYY'));
if (!empty($this->programs)) {
	foreach ($this->programs as $p) {
		if (count($kw)<5) {
			if (!in_array($p['title'], $kw))
				$kw[]= Xmltv_String::strtolower( htmlspecialchars( $p['title'], ENT_QUOTES, 'utf-8' ) );
		}
	}
}
$this->headMeta()->setName('keywords', implode(',', $kw) );
?>

<div id="programtable" class="row">

	<table class="table">
	
		<thead>
			<tr>
				<th>Начало</th>
				<th>Название</th>
			</tr>
		</thead>
		
		<tbody>
	<?php foreach ($this->items as $k=>$prog) {
	    ?>
	    	<tr>
	    		<td width="9%"><?php echo $this->escape( $prog['start']->toString("HH:mm") ); ?></td>
	    		<?php 
	    		$linkAttHref = $this->url( array(
	    			'channel'=>$prog['channel_alias'],
	    			'alias'=>$prog['alias']), 'default_listings_broadcast-day' );
	    		?>
	    		<td><?php echo $prog['category_title_single']; ?> <a href="<?php echo $linkAttHref; ?>"><?php echo $prog['title'] ?></a> <?php echo $prog['sub_title']; ?></td>
	    	</tr>
	    	<?php if (!empty($prog['desc'])) { ?>
	    	<tr>
	    		<td></td>
	    		<td><?php echo $this->escape( $prog['desc'] ); ?></td>
	    	</tr>
	    	<?php } ?>
	    <?php 
	} ?>
		</tbody>
	</table>
</div>
