<?php
/**
 * Partial to render ListingsController::programDayAction() 
 * similar programs listing item
 *
 * @author  Antony Repin <egeshisolutions@gmail.com>
 * @version $Id: week-similar.phtml,v 1.2 2013-03-14 06:09:55 developer Exp $
 *
 */

$oldChannelTitle=null;
foreach ($this->items as $single){
    
	$channelUrl   = $this->url( array( 'channel'=>$single['channel_alias'] ), 'default_listings_day-listing' );
	$channelTitle = $this->escape( $single['channel_title'] );

	if (!$oldChannelTitle || ($channelTitle!=$oldChannelTitle)) {
		$oldChannelTitle=$channelTitle;
		printf( '<h3>Похожие передачи в другое время на этой неделе на канале <a href="%s" title="Передачи телеканала %s сегодня"><strong>%s</strong></a></h3>', $channelUrl, $oldChannelTitle, $oldChannelTitle);
	}

	$channelIcon = $this->baseUrl('images/channel_logo/'.$single['channel_icon']);
	$date = $single['start']->toString("dd-MM-YYYY");
	$linkAttrHref = $this->url( array(
		'channel'=>$this->escape( $single['channel_alias']),
		'alias'=>$this->escape( $single['alias']),
		'date'=>$date), 'default_listings_broadcast-date');
	
	$day = Xmltv_String::ucfirst( $single['start']->toString( 'EEEE'));
	$startDate = Xmltv_String::ucfirst( $single['start']->toString( 'd MMMM'));
	$startTime = Xmltv_String::ucfirst( $single['start']->toString( 'HH:mm'));
	//$category = Xmltv_String::strtolower( $this->escape( $single['category_title_single'] ));
	$linkAttrTitle = $this->escape( sprintf( 'Передача «%s» на канале <i>%s</i>', $single['title'], $channelTitle ));
?><p><img src="<?php echo $channelIcon ?>" alt="<?php echo $channelTitle ?>" class="logo" />
<span class="label label-info"><?php echo $day; ?></span>&nbsp;
<?php echo $startDate ?>&nbsp;<u><?php echo $startTime; ?></u> 
<?php //echo $category ?>
<a href="<?php echo $linkAttrHref ?>" title="<?php echo $linkAttrTitle; ?>"><em><?php echo $single['title']; ?></em></a></p>
<?php 
} ?>