<?php
/**
 * Backend navigation partial
 * 
 * @uses Zend_Navigation_Page
 */


?>
<div class="btn-group">
<?php
foreach ($this->container as $page) {
    //var_dump($page->getResource());
	if ( $this->isAllowed($page->getResource()) ){
	    switch ($page->idAttr){
	    	default:
	        case 'back':
	    	    ?>
	    	    <button class="btn btn-mini" 
	    	    	type="button" 
	    	    	id="back"  
	    	    	<?php echo (null !== $page->get('onclick', null)) ? ' onclick="'.$page->get('onclick').'"' : null ; ?>>
	    	    		<?php echo $page->getLabel() ?></button>
	    	    <?php 
	    	break;

	        case 'apply':
	        case 'save':
	        case 'save-plus':
	            $onclick = "$('#articleForm input[name=do]').val('".$page->idAttr."'); $('articleForm').submit();";
	    	    ?>
	    	    <button class="btn btn-mini" 
	    	    	id="<?php echo $page->idAttr; ?>"><?php echo $page->getLabel() ?></button>
	    	    <?php 
	    	break;
	    }
	}
} ?></div>
