<?php include ("nav.phtml"); ?>
<h1>Дубликаты записей режиссеров</h1>

<?php 
if (!empty($this->origin) && !empty($this->clones)) { ?>
<table class="table table-bordered">
	<caption>Дубликаты записей</caption>
	<thead>
		<tr>
			<th>Id</th>
		    <th>Имя</th>
		    <th>Ср. имя</th>
		    <th>Фамилия</th>
		    <th>Поз.</th>
		    <th>Англ. имя</th>
		    <th>Удалить</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><?php echo $this->origin['id'] ?></td>
			<td><?php echo $this->origin['f_name'] ?></td>
			<td><?php echo $this->origin['m_name'] ?></td>
			<td><?php echo $this->origin['s_name'] ?></td>
			<td><?php echo $this->origin['rank'] ?></td>
			<td><?php echo $this->origin['name_en'] ?></td>
			<td><a href="/admin/duplicates/delete-director/id/<?php echo $this->origin['id'] ?>">Удалить</a></td>
		  </tr>
		  
		  <?php $i=1; foreach ($this->clones as $clone) : ?>
		  <tr>
		  	<td><?php echo $clone['id'] ?></td>
		    <td><?php echo $clone['f_name'] ?></td>
		    <td><?php echo $clone['m_name'] ?></td>
		    <td><?php echo $clone['s_name'] ?></td>
		    <td><?php echo $clone['rank'] ?></td>
		    <td><?php echo $clone['name_en'] ?></td>
		    <td><a href="/admin/duplicates/delete-director/id/<?php echo $clone['id'] ?>">Удалить</a></td>
		   </tr>
		  <?php $i++; endforeach; ?>
	  </tbody>
	  <tfoot>
	  	<tr>
	  		<td colspan="7">Всего записей: <?php echo $this->total ?></td>
	  	</tr>
	  	<tr>
	  		<td colspan="7">Обработано записей: <?php echo $this->processed ?> (<?php echo $this->processed_pct ?>%)</td>
	  	</tr>
	  </tfoot>
</table>
<?php 
} else { ?>
<h3>Дубликатов не найдено</h3>
<?php 
}?>