<?php //include ("nav.phtml"); ?>
<h1>Работа с дубликатами данных</h1>

<ul class="nav nav-pills">
	<li class="nav-header">Актеры</li>
	<li><a href="/admin/actors/duplicates">Дубликаты записей</a></li>
	<li><a href="/admin/actors/list">Список</a></li>
	<li class="nav-header">Режиссеры</li>
	<li><a href="/admin/directors/duplicates">Дубликаты записей</a></li>
	<li><a href="/admin/directors/list">Список</a></li>
</ul>