<h1>Работа с дубликатами данных</h1>
<table class="table table-bordered">
	<caption>Действия</caption>
	<tbody>
		<!--<tr>
			<td class="task" style="font-weight:bold;">Обработать короткие имена актеров</td>
			<td class="link"><a href="/admin/duplicates/actors-short-names">/admin/duplicates/actors-short-names</a></td>
		</tr>
		-->
		
		<tr>
			<td class="task" style="font-weight:bold;">Обработать дубликаты записей актеров</td>
			<td class="link"><a href="/admin/duplicates/actors">/admin/duplicates/actors</a></td>
		</tr>
		<tr>
			<td class="task" style="font-weight:bold;">Обработать дубликаты записей режиссеров</td>
			<td class="link"><a href="/admin/duplicates/directors">/admin/duplicates/directors</a></td>
		</tr>
		<tr>
			<td class="task" style="font-weight:bold;">Конвертировать имена актеров</td>
			<td class="link"><a href="/admin/duplicates/actors-names">/admin/duplicates/actors-names</a></td>
		</tr>
		<tr>
			<td class="task" style="font-weight:bold;">Конвертировать имена режиссеров</td>
			<td class="link"><a href="/admin/duplicates/directors-names">/admin/duplicates/directors-names</a></td>
		</tr>
	</tbody>
</table>