<?php 
$this->headScript()->appendFile('/js/schedule-processing.js');
$css = "#premiere_search button:before, #premiere_search button:after { clear: both; }
#premiere_search dd label { float:left; }";
//$this->headStyle()->appendStyle($css);
?>
<h1>Обработка расписаний</h1>

<div class="tabbable">
	<ul class="nav nav-tabs">
		<li class="active"><a href="#pane-re-parse" data-toggle="tab">Обработка названий</a></li>
		<!-- <li><a href="#pane-premieres-search" data-toggle="tab">Поиск премьер</a></li> -->
		<li><a href="#pane-delete-programs" data-toggle="tab">Удаление программ</a></li>
	</ul>
	<div class="tab-content">
		<div class="tab-pane active" id="pane-re-parse">
			<h3>Обработка названий</h3>
			<div>
				<?php 
					$button = new Zend_Form_Element_Button ( 'submit' );
					$button->setLabel( 'Старт' )
						->setAttribs(array(
							'id'=>'titles_parsing',
							'class'=>'btn btn-primary'
						))
						->removeDecorator('DtDdWrapper')
						->removeDecorator('Tooltip');
				
					$parseTitlesForm = new ZendX_JQuery_Form();
					$parseTitlesForm->addAttribs ( array (
						'id' => 'parse_titles' ) );
					
					$parsePremieres = new Zend_Form_Element_Checkbox( 'do_parse_premieres' );
					$parsePremieres->setLabel( 'Премьеры' )
						->setAttribs(array('class'=>'checkbox', 'id'=>'do_parse_premieres'));
						
					$parseDescriptions = new Zend_Form_Element_Checkbox( 'do_parse_descriptions' );
					$parseDescriptions->setLabel( 'Описания' )
						->setAttribs(array('class'=>'checkbox', 'id'=>'do_parse_descriptions'));
						
					$parseSeries = new Zend_Form_Element_Checkbox( 'do_parse_series' );
					$parseSeries->setLabel( 'Сериалы' )
						->setAttribs(array('class'=>'checkbox', 'id'=>'do_parse_series'));
					
					$parseMovies = new Zend_Form_Element_Checkbox( 'do_parse_movies' );
					$parseMovies->setLabel( 'Фильмы' )
						->setAttribs(array('class'=>'checkbox', 'id'=>'do_parse_movies'));
					
					$parseSports = new Zend_Form_Element_Checkbox( 'do_parse_sports' );
					$parseSports->setLabel( 'Спортивные программы' )
						->setAttribs(array('class'=>'checkbox', 'id'=>'do_parse_sports'));
						
					$parseBreaks = new Zend_Form_Element_Checkbox( 'do_parse_breaks' );
					$parseBreaks->setLabel( 'Перерывы' )
						->setAttribs(array('class'=>'checkbox', 'id'=>'do_parse_breaks'));
					
					$parseDocumentary = new Zend_Form_Element_Checkbox( 'do_parse_documentary' );
					$parseDocumentary->setLabel( 'Документалистика' )
						->setAttribs(array('class'=>'checkbox', 'id'=>'do_parse_documentary'));

					$parseCartoons = new Zend_Form_Element_Checkbox( 'do_parse_cartoons' );
					$parseCartoons->setLabel( 'Мультфильмы' )
						->setAttribs(array('class'=>'checkbox', 'id'=>'do_parse_cartoons'));
						
					$saveUpdates = new Zend_Form_Element_Checkbox( 'save_updates' );
					$saveUpdates->setLabel( 'Сохранять изменения' )
						->setAttribs(array('class'=>'checkbox', 'id'=>'save_updates'));
					
					$dateStart = new ZendX_JQuery_Form_Element_DatePicker( 'start_date');
					$dateStart->setLabel('Начальная дата');
					$dateEnd = new ZendX_JQuery_Form_Element_DatePicker( 'end_date');
					$dateEnd->setLabel('Финальная дата');
					
					$parseTitlesForm->addElements ( array(
						$dateStart,
						$dateEnd,
						$parsePremieres,
						$parseSeries,
						$parseMovies,
						$parseSports,
						$parseBreaks,
						$parseDocumentary,
						$parseDescriptions,
						$parseCartoons,
						$button,
						$saveUpdates,
					) );
					$parseTitlesForm->setDecorators ( array ('FormElements', 'Form' ) );
					echo $parseTitlesForm;
					
				?>
			</div>
		</div>
		
		<?php /*
		<div class="tab-pane" id="pane-premieres-search">
			<h3>Поиск премьер</h3>
			<div>
				<?php
				$form = new Zend_Form();
				$form->setAction ( '' )
					->setMethod ( 'post' )
					->addAttribs ( array (
						'id' => 'premiere_search' ) );
				
				$options = new Zend_Form_Element_Radio( 'type' );
				$options->addMultiOptions( array(
					array('key'=>'fast', 'value'=>'Быстрый поиск'),
					array('key'=>'full', 'value'=>'Полный поиск')) )
					->setLabel( 'Тип поиска' );
							
				$button->setLabel( 'Начать поиск' )
					->setAttribs(array(
						'id'=>'start-search',
						'class'=>'btn btn-primary'
					))
					//->removeDecorator('DtDdWrapper')
					->removeDecorator('Tooltip');
				$form->addElements ( array($options, $button) );
				$form->setDecorators ( array ('FormElements', 'Form' ) );
				echo $form;
				?>
			</div>
		</div>
		*/ ?>
		
		<div class="tab-pane" id="pane-delete-programs">
			<h3>Удаление программ</h3>
			<div>
				<?php 
				$cleanupForm = new ZendX_JQuery_Form();
				$cleanupForm->setAction ( '' )
					->setMethod ( 'post' )
					->addAttribs ( array (
						'id' => 'delete_programs' ) );
					
				$cleanPrograms = new Zend_Form_Element_Checkbox( 'delete-programs' );
				$cleanPrograms->setLabel( 'Удалить программы' )
					->setRequired()
					->setAttribs(array('class'=>'checkbox', 'id'=>'delete-programs'));
				
				$cleanData = new Zend_Form_Element_Checkbox( 'delete-info' );
				$cleanData->setLabel( 'Удалить свойства программ?' )
					->setRequired()
					->setAttribs(array('class'=>'checkbox', 'id'=>'delete-info'));
				
				$button->setLabel( 'Старт' )->setAttribs(array( 'id'=>'delete_start_btn', 'class'=>'btn btn-primary' ));
				
				$dateStart = new ZendX_JQuery_Form_Element_DatePicker( 'delete_start');
				$dateStart->setLabel('Начальная дата');
				$dateEnd = new ZendX_JQuery_Form_Element_DatePicker( 'delete_end');
				$dateEnd->setLabel('Финальная дата');

							
					
				$cleanupForm->addElements ( array($dateStart, $dateEnd, $cleanPrograms, $cleanData, $button) );
				echo $cleanupForm;
				?>
			</div>
		</div>
		
	</div>
</div>
<?php /*
<table class="table table-bordered">
	<caption>Действия</caption>
	<thead>
		<tr>
			<th>Поиск премьер</th>
			<th>Нормализация</th>
			<th>Удаление программ</th>
			<th>Удаление ВСЕХ описаний</th>
			<th>Удаление ВСЕХ свойств программ</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>
				<?php
				$form = new Zend_Form();
				$form->setAction ( '' )
					->setMethod ( 'post' )
					->addAttribs ( array (
						'id' => 'premiere_search' ) );
				
				$options = new Zend_Form_Element_Radio( 'type' );
				$options->addMultiOptions( array(
					array('key'=>'fast', 'value'=>'Быстрый поиск'),
					array('key'=>'full', 'value'=>'Полный поиск')) )
					->setLabel( 'Тип поиска' );
							
				$button = new Zend_Form_Element_Button ( 'submit' );
				$button->setLabel( 'Начать поиск' )
					->setAttribs(array(
						'id'=>'start-search',
						'class'=>'btn btn-primary'
					))
					->removeDecorator('DtDdWrapper')
					->removeDecorator('Tooltip');
				$form->addElements ( array($options, $button) );
				$form->setDecorators ( array ('FormElements', 'Form' ) );
				echo $form;
				?>
			</td>
			
			<td></td>
			
			<td>
				<?php 
				$cleanupForm = new ZendX_JQuery_Form();
				$cleanupForm->setAction ( '' )
					->setMethod ( 'post' )
					->addAttribs ( array (
						'id' => 'delete_programs' ) );
					
				$cleanPrograms = new Zend_Form_Element_Checkbox( 'delete-programs' );
				$cleanPrograms->setLabel( 'Удалить программы' )
					->setRequired()
					->setAttribs(array('class'=>'checkbox', 'id'=>'delete-programs'));
				
				$cleanData = new Zend_Form_Element_Checkbox( 'delete-info' );
				$cleanData->setLabel( 'Удалить свойства программ?' )
					->setRequired()
					->setAttribs(array('class'=>'checkbox', 'id'=>'delete-info'));
				
				$button = new Zend_Form_Element_Button ( 'submit' );
				$button->setLabel( 'Старт' )
					->setAttribs(array(
						'id'=>'delete_start_btn',
						'class'=>'btn btn-primary'
					))
					//->removeDecorator('DtDdWrapper')
					->removeDecorator('Tooltip');
				
				$dateStart = new ZendX_JQuery_Form_Element_DatePicker( 'delete_start');
				$dateStart->setLabel('Дата начала');
				$dateEnd = new ZendX_JQuery_Form_Element_DatePicker( 'delete_end');
				$dateEnd->setLabel('Дата конца');

							
					
				$cleanupForm->addElements ( array($dateStart, $dateEnd, $cleanPrograms, $cleanData, $button) );
				echo $cleanupForm;
				?>
			</td>
			
			<td></td>
			<td></td>
		</tr>
	</tbody>
</table>
*/ ?>
<div id="result"></div>
