<?php 
/**
 * Admin backend import ciew script
 * 
 * @author     Antony Repin <egeshisolutions@gmail.com>
 * @subpackage backend
 * @version    $Id: index.phtml,v 1.2 2013-03-17 18:34:58 developer Exp $
 */

$this->headScript()
	->appendScript("
	jQuery(function($){
	$('.remote').click(function(){
		$.ajax({
			url: '".$this->baseUrl('admin/import/remote/site/teleguide')."',
			data: 'format=html',
			type: 'get',
			dataType: 'html',
			beforeSend: function(){
				$('#result').css({ 'background':'lightYellow' }).html(\"<h3>Происходит импорт</h3>\");
			},
			success: function(response){
				$('#result').css({ \"background-color\":\"lightGreen\" }).html(response);
			},
			error: function(XHR, textStatus, errorThrown){
				$('#result').css({ \"background-color\":\"lightRed\" }).html(XHR.responseText);
			}
		});
	});
});
	");
?>
<h2 class="page_heading">Загрузка XML</h2>
<?php echo $this->form ?>
<a class="remote" id="teleguide" href="#">Загрузить файл с teleguide.info</a>
<div id="result"></div>