<div id="nav">
	<ul class="nav nav-pills">
		<li><a href="/admin">Главная</a></li>
		<li><a href="/admin/programs">Программы</a></li>
		<li><a href="/admin/channels">Каналы</a></li>
		<li><a href="/admin/series">Фильмы</a></li>
		<li><a href="/admin/movies">Сериалы</a></li>
		<li><a href="/admin/comments">Комменты</a></li>
		<li class="dropdown">
			<a class="dropdown-toggle" href="#" data-toggle="dropdown">Актеры<b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li><a href="/admin/actors/list">Список</a></li>
				<li><a href="/admin/actors/duplicates">Дубликаты</a></li>
			</ul>
		</li>
		<li class="dropdown">
			<a class="dropdown-toggle" href="#" data-toggle="dropdown">Режиссеры<b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li><a href="/admin/directors/list">Список</a></li>
				<li><a href="/admin/directors/duplicates">Дубликаты</a></li>
			</ul>
		</li>
		<li><a href="/admin/duplicates">Дубликаты записей</a></li>
		<li class="active"><a href="/admin/import">Импорт XML</a></li>
	</ul>
</div>