<?php $this->headScript()->appendFile($this->baseUrl().'/js/parsexml.js'); ?>
<?php include ("nav.phtml"); ?>

<h1>Импорт XML</h1>

<table class="table table-bordered">
	<caption>Загруженный файл</caption>
	<tbody>
		<tr>
			<td>Файл:&nbsp;</td>
			<td><?php
			echo $this->file_info ['filename']?></td>
		</tr>
		<tr>
			<td>Размер:&nbsp;</td>
			<td><?php
			echo $this->file_info ['filesize']?></td>
		</tr>
	</tbody>
</table>

<table class="table table-bordered">
	<caption>Системные переменные</caption>
	<tbody>
		<tr>
			<td>memory_limit</td>
			<td><?php echo ini_get('memory_limit') ?></td>
		</tr>
		<tr>
			<td>max_execution_time</td>
			<td><?php echo ini_get('max_execution_time') ?></td>
		</tr>
		<tr>
			<td>max_input_time</td>
			<td><?php echo ini_get('max_input_time') ?></td>
		</tr>
	</tbody>
</table>
<?php
if ($this->show_continue) {
	try {
		$channels_form = new Zend_Form ();
		$channels_form->setAction ( '' )
			->setMethod ( 'post' )
			->addAttribs ( array (
				'id' => 'parse_channels',
				'onSubmit' => 'validate(this)' ) );
		$channels_button = new Zend_Form_Element_Submit ( 'submit', array (
			'id' => 'parsechannels',
			'class' => 'btn btn-primary' ) );
		$channels_button->setLabel ( 'Обработка каналов' )->setDecorators ( array (  array (
		 	'ViewHelper', array (
		 		'helper' => 'formSubmit' 
		) ) ) );
		$channels_form->addElement ( $channels_button );
		
		//  add file field
		$xml_file_ch = new Zend_Form_Element_Hidden ( 'xml_file_ch', array (
			'value' => $this->file_info ['filename'] ) );
		$xml_file_pr = new Zend_Form_Element_Hidden ( 'xml_file_pr', array (
			'value' => $this->file_info ['filename'] ) );
		$channels_form->addElement ( $xml_file_ch );
		
		
		//$channels_form->addElement ( $xml_file );
		//$channels_form->setDecorators ( array ('FormElements', 'Form' ) );
		
		$programs_form = new Zend_Form ();
		$programs_form->setAction ( '' )
			->setMethod ( 'post' )
			->addAttribs ( array (
				'id' => 'parse_programs',
				'onSubmit' => 'validate(this)' ) );
		$programs_button = new Zend_Form_Element_Submit ( 'submit', array (
			'id' => 'parseprograms',
			'class' => 'btn btn-primary' ) );
		$programs_button->setLabel ( 'Обработка программ' )->setDecorators ( array (  array (
		 	'ViewHelper', array (
		 		'helper' => 'formSubmit' 
		) ) ) );
		$programs_form->addElement ( $programs_button );
		$programs_form->setDecorators ( array ('FormElements', 'Form' ) );
		$programs_form->addElement ( $xml_file_pr );
		
	} catch ( Exception $e ) {
		echo $e->getMessage ();
	}
	
	echo $channels_form;
	echo $programs_form;
}
?>
<div id="progress" style="padding: 6px; display: none; background-color: lightYellow;"></div>
<div id="parseerrors" style="padding: 6px; background-color: #FFB5BE; display: none;"></div>
<?php
/*$js = "



";
*/
//$this->inlineScript ()->appendScript ( $js );
?>