<?php $this->headScript()->appendFile($this->baseUrl().'/js/parsexml.js'); ?>

<h1>Импорт XML</h1>

<table class="table table-bordered">
	<caption>Загруженный файл</caption>
	<tbody>
		<tr>
			<td>Файл:&nbsp;</td>
			<td><?php
			echo $this->file_info ['filename']?></td>
		</tr>
		<tr>
			<td>Размер:&nbsp;</td>
			<td><?php
			echo $this->file_info ['filesize']?></td>
		</tr>
	</tbody>
</table>

<table class="table table-bordered">
	<caption>Системные переменные</caption>
	<tbody>
		<tr>
			<td>memory_limit</td>
			<td><?php echo ini_get('memory_limit') ?></td>
		</tr>
		<tr>
			<td>max_execution_time</td>
			<td><?php echo ini_get('max_execution_time') ?></td>
		</tr>
		<tr>
			<td>max_input_time</td>
			<td><?php echo ini_get('max_input_time') ?></td>
		</tr>
	</tbody>
</table>
<?php
if ($this->show_continue) {
	try {
		/*
		 * Parse channels button
		 */
		$channels_form = new Zend_Form ();
		$channels_form->setAction ( '' )
			->setMethod ( 'post' )
			->addAttribs ( array (
				'id' => 'parse_channels',
				'onSubmit' => 'validate(this)' ) );
		$button = new Zend_Form_Element_Button ( 'submit' );
		$button->setLabel ( 'Обработка каналов' )
			->setAttribs(array (
				'id' => 'parsechannels',
				'class' => 'btn btn-primary' ));
		$channels_form->addElement ( $button );
		
		//  add file field
		$xml_file = new Zend_Form_Element_Hidden ( 'xml_file', array (
			'value' => $this->file_info ['filename'] ) );
		$channels_form->addElement ( $xml_file );
		
		
		//$channels_form->addElement ( $xml_file );
		//$channels_form->setDecorators ( array ('FormElements', 'Form' ) );
		
		/*
		 * Parse programs button
		 */
		$programs_form = new Zend_Form ();
		$programs_form->setAction ( '' )
			->setMethod ( 'post' )
			->addAttribs ( array (
				'id' => 'parse_programs',
				'onSubmit' => 'validate(this)' ) );
		$button = new Zend_Form_Element_Button ( 'submit' );
		$button->setLabel ( 'Обработка программ' )
			->setAttribs(array (
				'id' => 'parseprograms',
				'class' => 'btn btn-primary' ));
		$programs_form->addElement ( $button );
		$programs_form->setDecorators ( array ('FormElements', 'Form' ) );
		$programs_form->addElement ( $xml_file );
		
		/*
		 * Search for premieres button
		 */
		/*
		$premieres_form = new Zend_Form ();
		$premieres_form->setAction ( '' )
			->setMethod ( 'post' )
			->addAttribs ( array ( 'id' => 'premieres_search' ) );
		$button = new Zend_Form_Element_Button ( 'submit' );
		$button->setLabel ( 'Поиск премьер' )
			->setAttribs(array(
				'id'=>'premieres_start_search',
				'class'=>'btn btn-primary'
			));
		$premieres_form->addElement ( $button );
		$premieres_form->setDecorators ( array ('FormElements', 'Form' ) );
		$premieres_form->addElement ( $xml_file );
		*/
	} catch ( Exception $e ) {
		echo $e->getMessage ();
	}
	
	echo $channels_form;
	echo $programs_form;
	//echo $premieres_form;
}
?>
<div id="progress" style="padding: 6px; display: none; background-color: lightYellow;"></div>
<div id="zend-progressbar-container">
    <div id="parsecounter"></div>
</div>
<div id="parseerrors" style="padding: 6px; background-color: #FFB5BE; display: none;"></div>
<?php
/*$js = "



";
*/
//$this->inlineScript ()->appendScript ( $js );
?>